package gay.mountainspring.item.group;

import gay.mountainspring.aquifer.Aquifer;
import gay.mountainspring.item.MSItems;
import gay.mountainspring.sswplus.item.SSWPItems;
import net.fabricmc.fabric.api.itemgroup.v1.ItemGroupEvents;
import net.minecraft.item.ItemGroups;
import net.minecraft.item.Items;

public class MSVanillaGroups {
	public MSVanillaGroups() {}
	
	public static void init () {
		ItemGroupEvents.modifyEntriesEvent(ItemGroups.BUILDING_BLOCKS).register(Aquifer.MOUNTAINSPRING_ID, entries -> {
			entries.addAfter(Items.STONE_BUTTON,
					MSItems.MOSSY_STONE,
					MSItems.MOSSY_STONE_STAIRS,
					MSItems.MOSSY_STONE_SLAB,
					MSItems.MOSSY_STONE_WALL);
			entries.addAfter(Items.MOSSY_STONE_BRICK_WALL,
					MSItems.CRACKED_MOSSY_STONE_BRICKS,
					MSItems.CRACKED_MOSSY_STONE_BRICK_STAIRS,
					MSItems.CRACKED_MOSSY_STONE_BRICK_SLAB,
					MSItems.CRACKED_MOSSY_STONE_BRICK_WALL);
			entries.addAfter(SSWPItems.CHISELED_STONE_BRICK_WALL,
					MSItems.CRACKED_CHISELED_STONE_BRICKS,
					MSItems.CRACKED_CHISELED_STONE_BRICK_STAIRS,
					MSItems.CRACKED_CHISELED_STONE_BRICK_SLAB,
					MSItems.CRACKED_CHISELED_STONE_BRICK_WALL,
					MSItems.MOSSY_CHISELED_STONE_BRICKS,
					MSItems.MOSSY_CHISELED_STONE_BRICK_STAIRS,
					MSItems.MOSSY_CHISELED_STONE_BRICK_SLAB,
					MSItems.MOSSY_CHISELED_STONE_BRICK_WALL,
					MSItems.CRACKED_MOSSY_CHISELED_STONE_BRICKS,
					MSItems.CRACKED_MOSSY_CHISELED_STONE_BRICK_STAIRS,
					MSItems.CRACKED_MOSSY_CHISELED_STONE_BRICK_SLAB,
					MSItems.CRACKED_MOSSY_CHISELED_STONE_BRICK_WALL);
			
			entries.addAfter(Items.GRANITE_WALL,
					MSItems.MOSSY_GRANITE,
					MSItems.MOSSY_GRANITE_STAIRS,
					MSItems.MOSSY_GRANITE_SLAB,
					MSItems.MOSSY_GRANITE_WALL,
					MSItems.COBBLED_GRANITE,
					MSItems.COBBLED_GRANITE_STAIRS,
					MSItems.COBBLED_GRANITE_SLAB,
					MSItems.COBBLED_GRANITE_WALL,
					MSItems.MOSSY_COBBLED_GRANITE,
					MSItems.MOSSY_COBBLED_GRANITE_STAIRS,
					MSItems.MOSSY_COBBLED_GRANITE_SLAB,
					MSItems.MOSSY_COBBLED_GRANITE_WALL);
			entries.addAfter(SSWPItems.POLISHED_GRANITE_WALL,
					MSItems.GRANITE_BRICKS,
					MSItems.GRANITE_BRICK_STAIRS,
					MSItems.GRANITE_BRICK_SLAB,
					MSItems.GRANITE_BRICK_WALL,
					MSItems.CRACKED_GRANITE_BRICKS,
					MSItems.CRACKED_GRANITE_BRICK_STAIRS,
					MSItems.CRACKED_GRANITE_BRICK_SLAB,
					MSItems.CRACKED_GRANITE_BRICK_WALL,
					MSItems.MOSSY_GRANITE_BRICKS,
					MSItems.MOSSY_GRANITE_BRICK_STAIRS,
					MSItems.MOSSY_GRANITE_BRICK_SLAB,
					MSItems.MOSSY_GRANITE_BRICK_WALL,
					MSItems.CRACKED_MOSSY_GRANITE_BRICKS,
					MSItems.CRACKED_MOSSY_GRANITE_BRICK_STAIRS,
					MSItems.CRACKED_MOSSY_GRANITE_BRICK_SLAB,
					MSItems.CRACKED_MOSSY_GRANITE_BRICK_WALL);
			
			entries.addAfter(Items.DIORITE_WALL,
					MSItems.MOSSY_DIORITE,
					MSItems.MOSSY_DIORITE_STAIRS,
					MSItems.MOSSY_DIORITE_SLAB,
					MSItems.MOSSY_DIORITE_WALL,
					MSItems.COBBLED_DIORITE,
					MSItems.COBBLED_DIORITE_STAIRS,
					MSItems.COBBLED_DIORITE_SLAB,
					MSItems.COBBLED_DIORITE_WALL,
					MSItems.MOSSY_COBBLED_DIORITE,
					MSItems.MOSSY_COBBLED_DIORITE_STAIRS,
					MSItems.MOSSY_COBBLED_DIORITE_SLAB,
					MSItems.MOSSY_COBBLED_DIORITE_WALL);
			entries.addAfter(SSWPItems.POLISHED_DIORITE_WALL,
					MSItems.DIORITE_BRICKS,
					MSItems.DIORITE_BRICK_STAIRS,
					MSItems.DIORITE_BRICK_SLAB,
					MSItems.DIORITE_BRICK_WALL,
					MSItems.CRACKED_DIORITE_BRICKS,
					MSItems.CRACKED_DIORITE_BRICK_STAIRS,
					MSItems.CRACKED_DIORITE_BRICK_SLAB,
					MSItems.CRACKED_DIORITE_BRICK_WALL,
					MSItems.MOSSY_DIORITE_BRICKS,
					MSItems.MOSSY_DIORITE_BRICK_STAIRS,
					MSItems.MOSSY_DIORITE_BRICK_SLAB,
					MSItems.MOSSY_DIORITE_BRICK_WALL,
					MSItems.CRACKED_MOSSY_DIORITE_BRICKS,
					MSItems.CRACKED_MOSSY_DIORITE_BRICK_STAIRS,
					MSItems.CRACKED_MOSSY_DIORITE_BRICK_SLAB,
					MSItems.CRACKED_MOSSY_DIORITE_BRICK_WALL);
			
			entries.addAfter(Items.ANDESITE_WALL,
					MSItems.MOSSY_ANDESITE,
					MSItems.MOSSY_ANDESITE_STAIRS,
					MSItems.MOSSY_ANDESITE_SLAB,
					MSItems.MOSSY_ANDESITE_WALL,
					MSItems.COBBLED_ANDESITE,
					MSItems.COBBLED_ANDESITE_STAIRS,
					MSItems.COBBLED_ANDESITE_SLAB,
					MSItems.COBBLED_ANDESITE_WALL,
					MSItems.MOSSY_COBBLED_ANDESITE,
					MSItems.MOSSY_COBBLED_ANDESITE_STAIRS,
					MSItems.MOSSY_COBBLED_ANDESITE_SLAB,
					MSItems.MOSSY_COBBLED_ANDESITE_WALL);
			entries.addAfter(SSWPItems.POLISHED_ANDESITE_WALL,
					MSItems.ANDESITE_BRICKS,
					MSItems.ANDESITE_BRICK_STAIRS,
					MSItems.ANDESITE_BRICK_SLAB,
					MSItems.ANDESITE_BRICK_WALL,
					MSItems.CRACKED_ANDESITE_BRICKS,
					MSItems.CRACKED_ANDESITE_BRICK_STAIRS,
					MSItems.CRACKED_ANDESITE_BRICK_SLAB,
					MSItems.CRACKED_ANDESITE_BRICK_WALL,
					MSItems.MOSSY_ANDESITE_BRICKS,
					MSItems.MOSSY_ANDESITE_BRICK_STAIRS,
					MSItems.MOSSY_ANDESITE_BRICK_SLAB,
					MSItems.MOSSY_ANDESITE_BRICK_WALL,
					MSItems.CRACKED_MOSSY_ANDESITE_BRICKS,
					MSItems.CRACKED_MOSSY_ANDESITE_BRICK_STAIRS,
					MSItems.CRACKED_MOSSY_ANDESITE_BRICK_SLAB,
					MSItems.CRACKED_MOSSY_ANDESITE_BRICK_WALL);
			
			entries.addAfter(SSWPItems.DEEPSLATE_WALL,
					MSItems.MOSSY_DEEPSLATE,
					MSItems.MOSSY_DEEPSLATE_STAIRS,
					MSItems.MOSSY_DEEPSLATE_SLAB,
					MSItems.MOSSY_DEEPSLATE_WALL);
			entries.addAfter(Items.COBBLED_DEEPSLATE_WALL,
					MSItems.MOSSY_COBBLED_DEEPSLATE,
					MSItems.MOSSY_COBBLED_DEEPSLATE_STAIRS,
					MSItems.MOSSY_COBBLED_DEEPSLATE_SLAB,
					MSItems.MOSSY_COBBLED_DEEPSLATE_WALL);
			entries.addAfter(SSWPItems.CRACKED_DEEPSLATE_BRICK_WALL,
					MSItems.MOSSY_DEEPSLATE_BRICKS,
					MSItems.MOSSY_DEEPSLATE_BRICK_STAIRS,
					MSItems.MOSSY_DEEPSLATE_BRICK_SLAB,
					MSItems.MOSSY_DEEPSLATE_BRICK_WALL,
					MSItems.CRACKED_MOSSY_DEEPSLATE_BRICKS,
					MSItems.CRACKED_MOSSY_DEEPSLATE_BRICK_STAIRS,
					MSItems.CRACKED_MOSSY_DEEPSLATE_BRICK_SLAB,
					MSItems.CRACKED_MOSSY_DEEPSLATE_BRICK_WALL);
			entries.addAfter(SSWPItems.CRACKED_DEEPSLATE_TILE_WALL,
					MSItems.MOSSY_DEEPSLATE_TILES,
					MSItems.MOSSY_DEEPSLATE_TILE_STAIRS,
					MSItems.MOSSY_DEEPSLATE_TILE_SLAB,
					MSItems.MOSSY_DEEPSLATE_TILE_WALL,
					MSItems.CRACKED_MOSSY_DEEPSLATE_TILES,
					MSItems.CRACKED_MOSSY_DEEPSLATE_TILE_STAIRS,
					MSItems.CRACKED_MOSSY_DEEPSLATE_TILE_SLAB,
					MSItems.CRACKED_MOSSY_DEEPSLATE_TILE_WALL);
			
			entries.addAfter(Items.TUFF_WALL,
					MSItems.MOSSY_TUFF,
					MSItems.MOSSY_TUFF_STAIRS,
					MSItems.MOSSY_TUFF_SLAB,
					MSItems.MOSSY_TUFF_WALL);
			entries.addAfter(Items.TUFF_BRICK_WALL,
					MSItems.CRACKED_TUFF_BRICKS,
					MSItems.CRACKED_TUFF_BRICK_STAIRS,
					MSItems.CRACKED_TUFF_BRICK_SLAB,
					MSItems.CRACKED_TUFF_BRICK_WALL,
					MSItems.MOSSY_TUFF_BRICKS,
					MSItems.MOSSY_TUFF_BRICK_STAIRS,
					MSItems.MOSSY_TUFF_BRICK_SLAB,
					MSItems.MOSSY_TUFF_BRICK_WALL,
					MSItems.CRACKED_MOSSY_TUFF_BRICKS,
					MSItems.CRACKED_MOSSY_TUFF_BRICK_STAIRS,
					MSItems.CRACKED_MOSSY_TUFF_BRICK_SLAB,
					MSItems.CRACKED_MOSSY_TUFF_BRICK_WALL);
			entries.addAfter(SSWPItems.CHISELED_TUFF_BRICK_WALL,
					MSItems.CRACKED_CHISELED_TUFF_BRICKS,
					MSItems.CRACKED_CHISELED_TUFF_BRICK_STAIRS,
					MSItems.CRACKED_CHISELED_TUFF_BRICK_SLAB,
					MSItems.CRACKED_CHISELED_TUFF_BRICK_WALL,
					MSItems.MOSSY_CHISELED_TUFF_BRICKS,
					MSItems.MOSSY_CHISELED_TUFF_BRICK_STAIRS,
					MSItems.MOSSY_CHISELED_TUFF_BRICK_SLAB,
					MSItems.MOSSY_CHISELED_TUFF_BRICK_WALL,
					MSItems.CRACKED_MOSSY_CHISELED_TUFF_BRICKS,
					MSItems.CRACKED_MOSSY_CHISELED_TUFF_BRICK_STAIRS,
					MSItems.CRACKED_MOSSY_CHISELED_TUFF_BRICK_SLAB,
					MSItems.CRACKED_MOSSY_CHISELED_TUFF_BRICK_WALL);
			
			entries.addAfter(Items.BRICK_WALL,
					MSItems.CRACKED_BRICKS,
					MSItems.CRACKED_BRICK_STAIRS,
					MSItems.CRACKED_BRICK_SLAB,
					MSItems.CRACKED_BRICK_WALL);
			
			entries.addAfter(Items.MUD_BRICK_WALL,
					MSItems.CRACKED_MUD_BRICKS,
					MSItems.CRACKED_MUD_BRICK_STAIRS,
					MSItems.CRACKED_MUD_BRICK_SLAB,
					MSItems.CRACKED_MUD_BRICK_WALL);
			
			entries.addAfter(SSWPItems.CUT_SANDSTONE_WALL,
					MSItems.SANDSTONE_BRICKS,
					MSItems.SANDSTONE_BRICK_STAIRS,
					MSItems.SANDSTONE_BRICK_SLAB,
					MSItems.SANDSTONE_BRICK_WALL,
					MSItems.CRACKED_SANDSTONE_BRICKS,
					MSItems.CRACKED_SANDSTONE_BRICK_STAIRS,
					MSItems.CRACKED_SANDSTONE_BRICK_SLAB,
					MSItems.CRACKED_SANDSTONE_BRICK_WALL);
			
			entries.addAfter(SSWPItems.CUT_RED_SANDSTONE_WALL,
					MSItems.RED_SANDSTONE_BRICKS,
					MSItems.RED_SANDSTONE_BRICK_STAIRS,
					MSItems.RED_SANDSTONE_BRICK_SLAB,
					MSItems.RED_SANDSTONE_BRICK_WALL,
					MSItems.CRACKED_RED_SANDSTONE_BRICKS,
					MSItems.CRACKED_RED_SANDSTONE_BRICK_STAIRS,
					MSItems.CRACKED_RED_SANDSTONE_BRICK_SLAB,
					MSItems.CRACKED_RED_SANDSTONE_BRICK_WALL);
			
			entries.addAfter(SSWPItems.PRISMARINE_BRICK_WALL,
					MSItems.CRACKED_PRISMARINE_BRICKS,
					MSItems.CRACKED_PRISMARINE_BRICK_STAIRS,
					MSItems.CRACKED_PRISMARINE_BRICK_SLAB,
					MSItems.CRACKED_PRISMARINE_BRICK_WALL);
			
			entries.addAfter(SSWPItems.CHISELED_NETHER_BRICK_WALL,
					MSItems.CRACKED_CHISELED_NETHER_BRICKS,
					MSItems.CRACKED_CHISELED_NETHER_BRICK_STAIRS,
					MSItems.CRACKED_CHISELED_NETHER_BRICK_SLAB,
					MSItems.CRACKED_CHISELED_NETHER_BRICK_WALL);
			entries.addAfter(SSWPItems.RED_NETHER_BRICK_FENCE_GATE,
					MSItems.CRACKED_RED_NETHER_BRICKS,
					MSItems.CRACKED_RED_NETHER_BRICK_STAIRS,
					MSItems.CRACKED_RED_NETHER_BRICK_SLAB,
					MSItems.CRACKED_RED_NETHER_BRICK_WALL,
					MSItems.CRACKED_RED_NETHER_BRICK_FENCE,
					MSItems.CRACKED_RED_NETHER_BRICK_FENCE_GATE,
					MSItems.CHISELED_RED_NETHER_BRICKS,
					MSItems.CHISELED_RED_NETHER_BRICK_STAIRS,
					MSItems.CHISELED_RED_NETHER_BRICK_SLAB,
					MSItems.CHISELED_RED_NETHER_BRICK_WALL,
					MSItems.CRACKED_CHISELED_RED_NETHER_BRICKS,
					MSItems.CRACKED_CHISELED_RED_NETHER_BRICK_STAIRS,
					MSItems.CRACKED_CHISELED_RED_NETHER_BRICK_SLAB,
					MSItems.CRACKED_CHISELED_RED_NETHER_BRICK_WALL);
			
			entries.addAfter(Items.END_STONE_BRICK_WALL,
					MSItems.CRACKED_END_STONE_BRICKS,
					MSItems.CRACKED_END_STONE_BRICK_STAIRS,
					MSItems.CRACKED_END_STONE_BRICK_SLAB,
					MSItems.CRACKED_END_STONE_BRICK_WALL);
			
			entries.addAfter(SSWPItems.QUARTZ_BRICK_WALL,
					MSItems.CRACKED_QUARTZ_BRICKS,
					MSItems.CRACKED_QUARTZ_BRICK_STAIRS,
					MSItems.CRACKED_QUARTZ_BRICK_SLAB,
					MSItems.CRACKED_QUARTZ_BRICK_WALL);
		});
		
		ItemGroupEvents.modifyEntriesEvent(ItemGroups.FUNCTIONAL).register(Aquifer.MOUNTAINSPRING_ID, entries -> {
			entries.addAfter(Items.INFESTED_STONE, MSItems.INFESTED_MOSSY_STONE);
			entries.addAfter(Items.INFESTED_CRACKED_STONE_BRICKS,
					MSItems.INFESTED_CRACKED_MOSSY_STONE_BRICKS);
			entries.addAfter(Items.INFESTED_CHISELED_STONE_BRICKS,
					MSItems.INFESTED_MOSSY_CHISELED_STONE_BRICKS,
					MSItems.INFESTED_CRACKED_CHISELED_STONE_BRICKS,
					MSItems.INFESTED_CRACKED_MOSSY_CHISELED_STONE_BRICKS);
			
			entries.addAfter(SSWPItems.INFESTED_GRANITE,
					MSItems.INFESTED_MOSSY_GRANITE,
					MSItems.INFESTED_COBBLED_GRANITE,
					MSItems.INFESTED_MOSSY_COBBLED_GRANITE);
			entries.addAfter(SSWPItems.INFESTED_POLISHED_GRANITE,
					MSItems.GRANITE_BRICKS,
					MSItems.MOSSY_GRANITE_BRICKS,
					MSItems.CRACKED_GRANITE_BRICKS,
					MSItems.CRACKED_MOSSY_GRANITE_BRICKS);
			
			entries.addAfter(SSWPItems.INFESTED_DIORITE,
					MSItems.INFESTED_MOSSY_DIORITE,
					MSItems.INFESTED_COBBLED_DIORITE,
					MSItems.INFESTED_MOSSY_COBBLED_DIORITE);
			entries.addAfter(SSWPItems.INFESTED_POLISHED_DIORITE,
					MSItems.DIORITE_BRICKS,
					MSItems.MOSSY_DIORITE_BRICKS,
					MSItems.CRACKED_DIORITE_BRICKS,
					MSItems.CRACKED_MOSSY_DIORITE_BRICKS);
			
			entries.addAfter(SSWPItems.INFESTED_ANDESITE,
					MSItems.INFESTED_MOSSY_ANDESITE,
					MSItems.INFESTED_COBBLED_ANDESITE,
					MSItems.INFESTED_MOSSY_COBBLED_ANDESITE);
			entries.addAfter(SSWPItems.INFESTED_POLISHED_ANDESITE,
					MSItems.ANDESITE_BRICKS,
					MSItems.MOSSY_ANDESITE_BRICKS,
					MSItems.CRACKED_ANDESITE_BRICKS,
					MSItems.CRACKED_MOSSY_ANDESITE_BRICKS);
			
			entries.addAfter(Items.INFESTED_DEEPSLATE, MSItems.INFESTED_MOSSY_DEEPSLATE);
			entries.addAfter(SSWPItems.INFESTED_COBBLED_DEEPSLATE, MSItems.INFESTED_MOSSY_COBBLED_DEEPSLATE);
			entries.addAfter(SSWPItems.INFESTED_DEEPSLATE_BRICKS, MSItems.INFESTED_MOSSY_DEEPSLATE_BRICKS);
			entries.addAfter(SSWPItems.INFESTED_CRACKED_DEEPSLATE_BRICKS, MSItems.INFESTED_CRACKED_MOSSY_DEEPSLATE_BRICKS);
			entries.addAfter(SSWPItems.INFESTED_DEEPSLATE_TILES, MSItems.INFESTED_MOSSY_DEEPSLATE_TILES);
			entries.addAfter(SSWPItems.INFESTED_CRACKED_DEEPSLATE_TILES, MSItems.INFESTED_CRACKED_MOSSY_DEEPSLATE_TILES);
			
			entries.addAfter(SSWPItems.INFESTED_TUFF, MSItems.INFESTED_MOSSY_TUFF);
			entries.addAfter(SSWPItems.INFESTED_TUFF_BRICKS,
					MSItems.INFESTED_MOSSY_TUFF_BRICKS,
					MSItems.INFESTED_CRACKED_TUFF_BRICKS,
					MSItems.INFESTED_CRACKED_MOSSY_TUFF_BRICKS);
			entries.addAfter(SSWPItems.INFESTED_CHISELED_TUFF_BRICKS,
					MSItems.INFESTED_MOSSY_CHISELED_TUFF_BRICKS,
					MSItems.INFESTED_CRACKED_CHISELED_TUFF_BRICKS,
					MSItems.INFESTED_CRACKED_MOSSY_CHISELED_TUFF_BRICKS);
		});
	}
}