package gay.mountainspring.block;

import gay.mountainspring.MSMain;
import gay.mountainspring.aquifer.block.HotFloorBlock;
import gay.mountainspring.aquifer.block.HotFloorFenceBlock;
import gay.mountainspring.aquifer.block.HotFloorFenceGateBlock;
import gay.mountainspring.aquifer.block.HotFloorSlabBlock;
import gay.mountainspring.aquifer.block.HotFloorStairsBlock;
import gay.mountainspring.aquifer.block.HotFloorWallBlock;
import gay.mountainspring.aquifer.block.OrientableSlabBlock;
import gay.mountainspring.aquifer.block.OrientableStairsBlock;
import gay.mountainspring.sswplus.block.SSWPWoodTypes;
import net.minecraft.block.AbstractBlock;
import net.minecraft.block.Block;
import net.minecraft.block.Blocks;
import net.minecraft.block.FenceBlock;
import net.minecraft.block.FenceGateBlock;
import net.minecraft.block.InfestedBlock;
import net.minecraft.block.MapColor;
import net.minecraft.block.PillarBlock;
import net.minecraft.block.RotatedInfestedBlock;
import net.minecraft.block.SlabBlock;
import net.minecraft.block.StairsBlock;
import net.minecraft.block.WallBlock;
import net.minecraft.block.enums.NoteBlockInstrument;
import net.minecraft.block.piston.PistonBehavior;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.sound.BlockSoundGroup;
import net.minecraft.util.Identifier;

public class MSBlocks {
	private MSBlocks() {}
	
	public static void init() {}
	
	public static final Block MOSSY_STONE = register("mossy_stone", new Block(AbstractBlock.Settings.copy(Blocks.STONE)));
	public static final Block MOSSY_STONE_SLAB = register("mossy_stone_slab", new SlabBlock(AbstractBlock.Settings.copy(MOSSY_STONE)));
	public static final Block MOSSY_STONE_STAIRS = register("mossy_stone_stairs", new StairsBlock(MOSSY_STONE.getDefaultState(), AbstractBlock.Settings.copy(MOSSY_STONE)));
	public static final Block MOSSY_STONE_WALL = register("mossy_stone_wall", new WallBlock(AbstractBlock.Settings.copy(MOSSY_STONE).solid()));
	public static final Block CRACKED_MOSSY_STONE_BRICKS = register("cracked_mossy_stone_bricks", new Block(AbstractBlock.Settings.copy(Blocks.STONE_BRICKS)));
	public static final Block CRACKED_MOSSY_STONE_BRICK_SLAB = register("cracked_mossy_stone_brick_slab", new SlabBlock(AbstractBlock.Settings.copy(CRACKED_MOSSY_STONE_BRICKS)));
	public static final Block CRACKED_MOSSY_STONE_BRICK_STAIRS = register("cracked_mossy_stone_brick_stairs", new StairsBlock(CRACKED_MOSSY_STONE_BRICKS.getDefaultState(), AbstractBlock.Settings.copy(CRACKED_MOSSY_STONE_BRICKS)));
	public static final Block CRACKED_MOSSY_STONE_BRICK_WALL = register("cracked_mossy_stone_brick_wall", new WallBlock(AbstractBlock.Settings.copy(CRACKED_MOSSY_STONE_BRICKS).solid()));
	public static final Block CRACKED_CHISELED_STONE_BRICKS = register("cracked_chiseled_stone_bricks", new Block(AbstractBlock.Settings.copy(Blocks.CHISELED_STONE_BRICKS)));
	public static final Block CRACKED_CHISELED_STONE_BRICK_SLAB = register("cracked_chiseled_stone_brick_slab", new SlabBlock(AbstractBlock.Settings.copy(CRACKED_CHISELED_STONE_BRICKS)));
	public static final Block CRACKED_CHISELED_STONE_BRICK_STAIRS = register("cracked_chiseled_stone_brick_stairs", new StairsBlock(CRACKED_CHISELED_STONE_BRICKS.getDefaultState(), AbstractBlock.Settings.copy(CRACKED_CHISELED_STONE_BRICKS)));
	public static final Block CRACKED_CHISELED_STONE_BRICK_WALL = register("cracked_chiseled_stone_brick_wall", new WallBlock(AbstractBlock.Settings.copy(CRACKED_CHISELED_STONE_BRICKS).solid()));
	public static final Block MOSSY_CHISELED_STONE_BRICKS = register("mossy_chiseled_stone_bricks", new Block(AbstractBlock.Settings.copy(Blocks.CHISELED_STONE_BRICKS)));
	public static final Block MOSSY_CHISELED_STONE_BRICK_SLAB = register("mossy_chiseled_stone_brick_slab", new SlabBlock(AbstractBlock.Settings.copy(MOSSY_CHISELED_STONE_BRICKS)));
	public static final Block MOSSY_CHISELED_STONE_BRICK_STAIRS = register("mossy_chiseled_stone_brick_stairs", new StairsBlock(MOSSY_CHISELED_STONE_BRICKS.getDefaultState(), AbstractBlock.Settings.copy(MOSSY_CHISELED_STONE_BRICKS)));
	public static final Block MOSSY_CHISELED_STONE_BRICK_WALL = register("mossy_chiseled_stone_brick_wall", new WallBlock(AbstractBlock.Settings.copy(MOSSY_CHISELED_STONE_BRICKS).solid()));
	public static final Block CRACKED_MOSSY_CHISELED_STONE_BRICKS = register("cracked_mossy_chiseled_stone_bricks", new Block(AbstractBlock.Settings.copy(Blocks.CHISELED_STONE_BRICKS)));
	public static final Block CRACKED_MOSSY_CHISELED_STONE_BRICK_SLAB = register("cracked_mossy_chiseled_stone_brick_slab", new SlabBlock(AbstractBlock.Settings.copy(CRACKED_MOSSY_CHISELED_STONE_BRICKS)));
	public static final Block CRACKED_MOSSY_CHISELED_STONE_BRICK_STAIRS = register("cracked_mossy_chiseled_stone_brick_stairs", new StairsBlock(CRACKED_MOSSY_CHISELED_STONE_BRICKS.getDefaultState(), AbstractBlock.Settings.copy(CRACKED_MOSSY_CHISELED_STONE_BRICKS)));
	public static final Block CRACKED_MOSSY_CHISELED_STONE_BRICK_WALL = register("cracked_mossy_chiseled_stone_brick_wall", new WallBlock(AbstractBlock.Settings.copy(CRACKED_MOSSY_CHISELED_STONE_BRICKS).solid()));
	
	public static final Block MOSSY_GRANITE = register("mossy_granite", new Block(AbstractBlock.Settings.copy(Blocks.GRANITE)));
	public static final Block MOSSY_GRANITE_SLAB = register("mossy_granite_slab", new SlabBlock(AbstractBlock.Settings.copy(MOSSY_GRANITE)));
	public static final Block MOSSY_GRANITE_STAIRS = register("mossy_granite_stairs", new StairsBlock(MOSSY_GRANITE.getDefaultState(), AbstractBlock.Settings.copy(MOSSY_GRANITE)));
	public static final Block MOSSY_GRANITE_WALL = register("mossy_granite_wall", new WallBlock(AbstractBlock.Settings.copy(MOSSY_GRANITE).solid()));
	public static final Block COBBLED_GRANITE = register("cobbled_granite", new Block(AbstractBlock.Settings.create().mapColor(MapColor.DIRT_BROWN).instrument(NoteBlockInstrument.BASEDRUM).requiresTool().strength(2.0f, 6.0f)));
	public static final Block COBBLED_GRANITE_SLAB = register("cobbled_granite_slab", new SlabBlock(AbstractBlock.Settings.copy(COBBLED_GRANITE)));
	public static final Block COBBLED_GRANITE_STAIRS = register("cobbled_granite_stairs", new StairsBlock(COBBLED_GRANITE.getDefaultState(), AbstractBlock.Settings.copy(COBBLED_GRANITE)));
	public static final Block COBBLED_GRANITE_WALL = register("cobbled_granite_wall", new WallBlock(AbstractBlock.Settings.copy(COBBLED_GRANITE).solid()));
	public static final Block MOSSY_COBBLED_GRANITE = register("mossy_cobbled_granite", new Block(AbstractBlock.Settings.copy(COBBLED_GRANITE)));
	public static final Block MOSSY_COBBLED_GRANITE_SLAB = register("mossy_cobbled_granite_slab", new SlabBlock(AbstractBlock.Settings.copy(MOSSY_COBBLED_GRANITE)));
	public static final Block MOSSY_COBBLED_GRANITE_STAIRS = register("mossy_cobbled_granite_stairs", new StairsBlock(MOSSY_COBBLED_GRANITE.getDefaultState(), AbstractBlock.Settings.copy(MOSSY_COBBLED_GRANITE)));
	public static final Block MOSSY_COBBLED_GRANITE_WALL = register("mossy_cobbled_granite_wall", new WallBlock(AbstractBlock.Settings.copy(MOSSY_COBBLED_GRANITE).solid()));
	public static final Block GRANITE_BRICKS = register("granite_bricks", new Block(AbstractBlock.Settings.create().mapColor(MapColor.DIRT_BROWN).instrument(NoteBlockInstrument.BASEDRUM).requiresTool().strength(1.5f, 6.0f)));
	public static final Block GRANITE_BRICK_SLAB = register("granite_brick_slab", new SlabBlock(AbstractBlock.Settings.copy(GRANITE_BRICKS)));
	public static final Block GRANITE_BRICK_STAIRS = register("granite_brick_stairs", new StairsBlock(GRANITE_BRICKS.getDefaultState(), AbstractBlock.Settings.copy(GRANITE_BRICKS)));
	public static final Block GRANITE_BRICK_WALL = register("granite_brick_wall", new WallBlock(AbstractBlock.Settings.copy(GRANITE_BRICKS).solid()));
	public static final Block CRACKED_GRANITE_BRICKS = register("cracked_granite_bricks", new Block(AbstractBlock.Settings.copy(GRANITE_BRICKS)));
	public static final Block CRACKED_GRANITE_BRICK_SLAB = register("cracked_granite_brick_slab", new SlabBlock(AbstractBlock.Settings.copy(CRACKED_GRANITE_BRICKS)));
	public static final Block CRACKED_GRANITE_BRICK_STAIRS = register("cracked_granite_brick_stairs", new StairsBlock(CRACKED_GRANITE_BRICKS.getDefaultState(), AbstractBlock.Settings.copy(CRACKED_GRANITE_BRICKS)));
	public static final Block CRACKED_GRANITE_BRICK_WALL = register("cracked_granite_brick_wall", new WallBlock(AbstractBlock.Settings.copy(CRACKED_GRANITE_BRICKS).solid()));
	public static final Block MOSSY_GRANITE_BRICKS = register("mossy_granite_bricks", new Block(AbstractBlock.Settings.copy(GRANITE_BRICKS)));
	public static final Block MOSSY_GRANITE_BRICK_SLAB = register("mossy_granite_brick_slab", new SlabBlock(AbstractBlock.Settings.copy(MOSSY_GRANITE_BRICKS)));
	public static final Block MOSSY_GRANITE_BRICK_STAIRS = register("mossy_granite_brick_stairs", new StairsBlock(MOSSY_GRANITE_BRICKS.getDefaultState(), AbstractBlock.Settings.copy(MOSSY_GRANITE_BRICKS)));
	public static final Block MOSSY_GRANITE_BRICK_WALL = register("mossy_granite_brick_wall", new WallBlock(AbstractBlock.Settings.copy(MOSSY_GRANITE_BRICKS).solid()));
	public static final Block CRACKED_MOSSY_GRANITE_BRICKS = register("cracked_mossy_granite_bricks", new Block(AbstractBlock.Settings.copy(GRANITE_BRICKS)));
	public static final Block CRACKED_MOSSY_GRANITE_BRICK_SLAB = register("cracked_mossy_granite_brick_slab", new SlabBlock(AbstractBlock.Settings.copy(CRACKED_MOSSY_GRANITE_BRICKS)));
	public static final Block CRACKED_MOSSY_GRANITE_BRICK_STAIRS = register("cracked_mossy_granite_brick_stairs", new StairsBlock(CRACKED_MOSSY_GRANITE_BRICKS.getDefaultState(), AbstractBlock.Settings.copy(CRACKED_MOSSY_GRANITE_BRICKS)));
	public static final Block CRACKED_MOSSY_GRANITE_BRICK_WALL = register("cracked_mossy_granite_brick_wall", new WallBlock(AbstractBlock.Settings.copy(CRACKED_MOSSY_GRANITE_BRICKS).solid()));
	
	public static final Block MOSSY_DIORITE = register("mossy_diorite", new Block(AbstractBlock.Settings.copy(Blocks.DIORITE)));
	public static final Block MOSSY_DIORITE_SLAB = register("mossy_diorite_slab", new SlabBlock(AbstractBlock.Settings.copy(MOSSY_DIORITE)));
	public static final Block MOSSY_DIORITE_STAIRS = register("mossy_diorite_stairs", new StairsBlock(MOSSY_DIORITE.getDefaultState(), AbstractBlock.Settings.copy(MOSSY_DIORITE)));
	public static final Block MOSSY_DIORITE_WALL = register("mossy_diorite_wall", new WallBlock(AbstractBlock.Settings.copy(MOSSY_DIORITE).solid()));
	public static final Block COBBLED_DIORITE = register("cobbled_diorite", new Block(AbstractBlock.Settings.create().mapColor(MapColor.OFF_WHITE).instrument(NoteBlockInstrument.BASEDRUM).requiresTool().strength(2.0f, 6.0f)));
	public static final Block COBBLED_DIORITE_SLAB = register("cobbled_diorite_slab", new SlabBlock(AbstractBlock.Settings.copy(COBBLED_DIORITE)));
	public static final Block COBBLED_DIORITE_STAIRS = register("cobbled_diorite_stairs", new StairsBlock(COBBLED_DIORITE.getDefaultState(), AbstractBlock.Settings.copy(COBBLED_DIORITE)));
	public static final Block COBBLED_DIORITE_WALL = register("cobbled_diorite_wall", new WallBlock(AbstractBlock.Settings.copy(COBBLED_DIORITE).solid()));
	public static final Block MOSSY_COBBLED_DIORITE = register("mossy_cobbled_diorite", new Block(AbstractBlock.Settings.copy(COBBLED_DIORITE)));
	public static final Block MOSSY_COBBLED_DIORITE_SLAB = register("mossy_cobbled_diorite_slab", new SlabBlock(AbstractBlock.Settings.copy(MOSSY_COBBLED_DIORITE)));
	public static final Block MOSSY_COBBLED_DIORITE_STAIRS = register("mossy_cobbled_diorite_stairs", new StairsBlock(MOSSY_COBBLED_DIORITE.getDefaultState(), AbstractBlock.Settings.copy(MOSSY_COBBLED_DIORITE)));
	public static final Block MOSSY_COBBLED_DIORITE_WALL = register("mossy_cobbled_diorite_wall", new WallBlock(AbstractBlock.Settings.copy(MOSSY_COBBLED_DIORITE).solid()));
	public static final Block DIORITE_BRICKS = register("diorite_bricks", new Block(AbstractBlock.Settings.create().mapColor(MapColor.OFF_WHITE).instrument(NoteBlockInstrument.BASEDRUM).requiresTool().strength(1.5f, 6.0f)));
	public static final Block DIORITE_BRICK_SLAB = register("diorite_brick_slab", new SlabBlock(AbstractBlock.Settings.copy(DIORITE_BRICKS)));
	public static final Block DIORITE_BRICK_STAIRS = register("diorite_brick_stairs", new StairsBlock(DIORITE_BRICKS.getDefaultState(), AbstractBlock.Settings.copy(DIORITE_BRICKS)));
	public static final Block DIORITE_BRICK_WALL = register("diorite_brick_wall", new WallBlock(AbstractBlock.Settings.copy(DIORITE_BRICKS).solid()));
	public static final Block CRACKED_DIORITE_BRICKS = register("cracked_diorite_bricks", new Block(AbstractBlock.Settings.copy(DIORITE_BRICKS)));
	public static final Block CRACKED_DIORITE_BRICK_SLAB = register("cracked_diorite_brick_slab", new SlabBlock(AbstractBlock.Settings.copy(CRACKED_DIORITE_BRICKS)));
	public static final Block CRACKED_DIORITE_BRICK_STAIRS = register("cracked_diorite_brick_stairs", new StairsBlock(CRACKED_DIORITE_BRICKS.getDefaultState(), AbstractBlock.Settings.copy(CRACKED_DIORITE_BRICKS)));
	public static final Block CRACKED_DIORITE_BRICK_WALL = register("cracked_diorite_brick_wall", new WallBlock(AbstractBlock.Settings.copy(CRACKED_DIORITE_BRICKS).solid()));
	public static final Block MOSSY_DIORITE_BRICKS = register("mossy_diorite_bricks", new Block(AbstractBlock.Settings.copy(DIORITE_BRICKS)));
	public static final Block MOSSY_DIORITE_BRICK_SLAB = register("mossy_diorite_brick_slab", new SlabBlock(AbstractBlock.Settings.copy(MOSSY_DIORITE_BRICKS)));
	public static final Block MOSSY_DIORITE_BRICK_STAIRS = register("mossy_diorite_brick_stairs", new StairsBlock(MOSSY_DIORITE_BRICKS.getDefaultState(), AbstractBlock.Settings.copy(MOSSY_DIORITE_BRICKS)));
	public static final Block MOSSY_DIORITE_BRICK_WALL = register("mossy_diorite_brick_wall", new WallBlock(AbstractBlock.Settings.copy(MOSSY_DIORITE_BRICKS).solid()));
	public static final Block CRACKED_MOSSY_DIORITE_BRICKS = register("cracked_mossy_diorite_bricks", new Block(AbstractBlock.Settings.copy(DIORITE_BRICKS)));
	public static final Block CRACKED_MOSSY_DIORITE_BRICK_SLAB = register("cracked_mossy_diorite_brick_slab", new SlabBlock(AbstractBlock.Settings.copy(CRACKED_MOSSY_DIORITE_BRICKS)));
	public static final Block CRACKED_MOSSY_DIORITE_BRICK_STAIRS = register("cracked_mossy_diorite_brick_stairs", new StairsBlock(CRACKED_MOSSY_DIORITE_BRICKS.getDefaultState(), AbstractBlock.Settings.copy(CRACKED_MOSSY_DIORITE_BRICKS)));
	public static final Block CRACKED_MOSSY_DIORITE_BRICK_WALL = register("cracked_mossy_diorite_brick_wall", new WallBlock(AbstractBlock.Settings.copy(CRACKED_MOSSY_DIORITE_BRICKS).solid()));
	
	public static final Block MOSSY_ANDESITE = register("mossy_andesite", new Block(AbstractBlock.Settings.copy(Blocks.ANDESITE)));
	public static final Block MOSSY_ANDESITE_SLAB = register("mossy_andesite_slab", new SlabBlock(AbstractBlock.Settings.copy(MOSSY_ANDESITE)));
	public static final Block MOSSY_ANDESITE_STAIRS = register("mossy_andesite_stairs", new StairsBlock(MOSSY_ANDESITE.getDefaultState(), AbstractBlock.Settings.copy(MOSSY_ANDESITE)));
	public static final Block MOSSY_ANDESITE_WALL = register("mossy_andesite_wall", new WallBlock(AbstractBlock.Settings.copy(MOSSY_ANDESITE).solid()));
	public static final Block COBBLED_ANDESITE = register("cobbled_andesite", new Block(AbstractBlock.Settings.create().mapColor(MapColor.STONE_GRAY).instrument(NoteBlockInstrument.BASEDRUM).requiresTool().strength(2.0f, 6.0f)));
	public static final Block COBBLED_ANDESITE_SLAB = register("cobbled_andesite_slab", new SlabBlock(AbstractBlock.Settings.copy(COBBLED_ANDESITE)));
	public static final Block COBBLED_ANDESITE_STAIRS = register("cobbled_andesite_stairs", new StairsBlock(COBBLED_ANDESITE.getDefaultState(), AbstractBlock.Settings.copy(COBBLED_ANDESITE)));
	public static final Block COBBLED_ANDESITE_WALL = register("cobbled_andesite_wall", new WallBlock(AbstractBlock.Settings.copy(COBBLED_ANDESITE).solid()));
	public static final Block MOSSY_COBBLED_ANDESITE = register("mossy_cobbled_andesite", new Block(AbstractBlock.Settings.copy(COBBLED_ANDESITE)));
	public static final Block MOSSY_COBBLED_ANDESITE_SLAB = register("mossy_cobbled_andesite_slab", new SlabBlock(AbstractBlock.Settings.copy(MOSSY_COBBLED_ANDESITE)));
	public static final Block MOSSY_COBBLED_ANDESITE_STAIRS = register("mossy_cobbled_andesite_stairs", new StairsBlock(MOSSY_COBBLED_ANDESITE.getDefaultState(), AbstractBlock.Settings.copy(MOSSY_COBBLED_ANDESITE)));
	public static final Block MOSSY_COBBLED_ANDESITE_WALL = register("mossy_cobbled_andesite_wall", new WallBlock(AbstractBlock.Settings.copy(MOSSY_COBBLED_ANDESITE).solid()));
	public static final Block ANDESITE_BRICKS = register("andesite_bricks", new Block(AbstractBlock.Settings.create().mapColor(MapColor.STONE_GRAY).instrument(NoteBlockInstrument.BASEDRUM).requiresTool().strength(1.5f, 6.0f)));
	public static final Block ANDESITE_BRICK_SLAB = register("andesite_brick_slab", new SlabBlock(AbstractBlock.Settings.copy(ANDESITE_BRICKS)));
	public static final Block ANDESITE_BRICK_STAIRS = register("andesite_brick_stairs", new StairsBlock(ANDESITE_BRICKS.getDefaultState(), AbstractBlock.Settings.copy(ANDESITE_BRICKS)));
	public static final Block ANDESITE_BRICK_WALL = register("andesite_brick_wall", new WallBlock(AbstractBlock.Settings.copy(ANDESITE_BRICKS).solid()));
	public static final Block CRACKED_ANDESITE_BRICKS = register("cracked_andesite_bricks", new Block(AbstractBlock.Settings.copy(ANDESITE_BRICKS)));
	public static final Block CRACKED_ANDESITE_BRICK_SLAB = register("cracked_andesite_brick_slab", new SlabBlock(AbstractBlock.Settings.copy(CRACKED_ANDESITE_BRICKS)));
	public static final Block CRACKED_ANDESITE_BRICK_STAIRS = register("cracked_andesite_brick_stairs", new StairsBlock(CRACKED_ANDESITE_BRICKS.getDefaultState(), AbstractBlock.Settings.copy(CRACKED_ANDESITE_BRICKS)));
	public static final Block CRACKED_ANDESITE_BRICK_WALL = register("cracked_andesite_brick_wall", new WallBlock(AbstractBlock.Settings.copy(CRACKED_ANDESITE_BRICKS).solid()));
	public static final Block MOSSY_ANDESITE_BRICKS = register("mossy_andesite_bricks", new Block(AbstractBlock.Settings.copy(ANDESITE_BRICKS)));
	public static final Block MOSSY_ANDESITE_BRICK_SLAB = register("mossy_andesite_brick_slab", new SlabBlock(AbstractBlock.Settings.copy(MOSSY_ANDESITE_BRICKS)));
	public static final Block MOSSY_ANDESITE_BRICK_STAIRS = register("mossy_andesite_brick_stairs", new StairsBlock(MOSSY_ANDESITE_BRICKS.getDefaultState(), AbstractBlock.Settings.copy(MOSSY_ANDESITE_BRICKS)));
	public static final Block MOSSY_ANDESITE_BRICK_WALL = register("mossy_andesite_brick_wall", new WallBlock(AbstractBlock.Settings.copy(MOSSY_ANDESITE_BRICKS).solid()));
	public static final Block CRACKED_MOSSY_ANDESITE_BRICKS = register("cracked_mossy_andesite_bricks", new Block(AbstractBlock.Settings.copy(ANDESITE_BRICKS)));
	public static final Block CRACKED_MOSSY_ANDESITE_BRICK_SLAB = register("cracked_mossy_andesite_brick_slab", new SlabBlock(AbstractBlock.Settings.copy(CRACKED_MOSSY_ANDESITE_BRICKS)));
	public static final Block CRACKED_MOSSY_ANDESITE_BRICK_STAIRS = register("cracked_mossy_andesite_brick_stairs", new StairsBlock(CRACKED_MOSSY_ANDESITE_BRICKS.getDefaultState(), AbstractBlock.Settings.copy(CRACKED_MOSSY_ANDESITE_BRICKS)));
	public static final Block CRACKED_MOSSY_ANDESITE_BRICK_WALL = register("cracked_mossy_andesite_brick_wall", new WallBlock(AbstractBlock.Settings.copy(CRACKED_MOSSY_ANDESITE_BRICKS).solid()));
	
	public static final Block MOSSY_DEEPSLATE = register("mossy_deepslate", new PillarBlock(AbstractBlock.Settings.copy(Blocks.DEEPSLATE)));
	public static final Block MOSSY_DEEPSLATE_SLAB = register("mossy_deepslate_slab", new OrientableSlabBlock(AbstractBlock.Settings.copy(MOSSY_DEEPSLATE)));
	public static final Block MOSSY_DEEPSLATE_STAIRS = register("mossy_deepslate_stairs", new OrientableStairsBlock(MOSSY_DEEPSLATE.getDefaultState(), AbstractBlock.Settings.copy(MOSSY_DEEPSLATE)));
	public static final Block MOSSY_DEEPSLATE_WALL = register("mossy_deepslate_wall", new WallBlock(AbstractBlock.Settings.copy(MOSSY_DEEPSLATE).solid()));
	public static final Block MOSSY_COBBLED_DEEPSLATE = register("mossy_cobbled_deepslate", new Block(AbstractBlock.Settings.copy(Blocks.COBBLED_DEEPSLATE)));
	public static final Block MOSSY_COBBLED_DEEPSLATE_SLAB = register("mossy_cobbled_deepslate_slab", new SlabBlock(AbstractBlock.Settings.copy(MOSSY_COBBLED_DEEPSLATE)));
	public static final Block MOSSY_COBBLED_DEEPSLATE_STAIRS = register("mossy_cobbled_deepslate_stairs", new StairsBlock(MOSSY_COBBLED_DEEPSLATE.getDefaultState(), AbstractBlock.Settings.copy(MOSSY_COBBLED_DEEPSLATE)));
	public static final Block MOSSY_COBBLED_DEEPSLATE_WALL = register("mossy_cobbled_deepslate_wall", new WallBlock(AbstractBlock.Settings.copy(MOSSY_COBBLED_DEEPSLATE).solid()));
	public static final Block MOSSY_DEEPSLATE_BRICKS = register("mossy_deepslate_bricks", new Block(AbstractBlock.Settings.copy(Blocks.DEEPSLATE_BRICKS)));
	public static final Block MOSSY_DEEPSLATE_BRICK_SLAB = register("mossy_deepslate_brick_slab", new SlabBlock(AbstractBlock.Settings.copy(MOSSY_DEEPSLATE_BRICKS)));
	public static final Block MOSSY_DEEPSLATE_BRICK_STAIRS = register("mossy_deepslate_brick_stairs", new StairsBlock(MOSSY_DEEPSLATE_BRICKS.getDefaultState(), AbstractBlock.Settings.copy(MOSSY_DEEPSLATE_BRICKS)));
	public static final Block MOSSY_DEEPSLATE_BRICK_WALL = register("mossy_deepslate_brick_wall", new WallBlock(AbstractBlock.Settings.copy(MOSSY_DEEPSLATE_BRICKS).solid()));
	public static final Block CRACKED_MOSSY_DEEPSLATE_BRICKS = register("cracked_mossy_deepslate_bricks", new Block(AbstractBlock.Settings.copy(Blocks.DEEPSLATE_BRICKS)));
	public static final Block CRACKED_MOSSY_DEEPSLATE_BRICK_SLAB = register("cracked_mossy_deepslate_brick_slab", new SlabBlock(AbstractBlock.Settings.copy(CRACKED_MOSSY_DEEPSLATE_BRICKS)));
	public static final Block CRACKED_MOSSY_DEEPSLATE_BRICK_STAIRS = register("cracked_mossy_deepslate_brick_stairs", new StairsBlock(CRACKED_MOSSY_DEEPSLATE_BRICKS.getDefaultState(), AbstractBlock.Settings.copy(CRACKED_MOSSY_DEEPSLATE_BRICKS)));
	public static final Block CRACKED_MOSSY_DEEPSLATE_BRICK_WALL = register("cracked_mossy_deepslate_brick_wall", new WallBlock(AbstractBlock.Settings.copy(CRACKED_MOSSY_DEEPSLATE_BRICKS).solid()));
	public static final Block MOSSY_DEEPSLATE_TILES = register("mossy_deepslate_tiles", new Block(AbstractBlock.Settings.copy(Blocks.DEEPSLATE_TILES)));
	public static final Block MOSSY_DEEPSLATE_TILE_SLAB = register("mossy_deepslate_tile_slab", new SlabBlock(AbstractBlock.Settings.copy(MOSSY_DEEPSLATE_TILES)));
	public static final Block MOSSY_DEEPSLATE_TILE_STAIRS = register("mossy_deepslate_tile_stairs", new StairsBlock(MOSSY_DEEPSLATE_TILES.getDefaultState(), AbstractBlock.Settings.copy(MOSSY_DEEPSLATE_TILES)));
	public static final Block MOSSY_DEEPSLATE_TILE_WALL = register("mossy_deepslate_tile_wall", new WallBlock(AbstractBlock.Settings.copy(MOSSY_DEEPSLATE_TILES).solid()));
	public static final Block CRACKED_MOSSY_DEEPSLATE_TILES = register("cracked_mossy_deepslate_tiles", new Block(AbstractBlock.Settings.copy(Blocks.DEEPSLATE_TILES)));
	public static final Block CRACKED_MOSSY_DEEPSLATE_TILE_SLAB = register("cracked_mossy_deepslate_tile_slab", new SlabBlock(AbstractBlock.Settings.copy(CRACKED_MOSSY_DEEPSLATE_TILES)));
	public static final Block CRACKED_MOSSY_DEEPSLATE_TILE_STAIRS = register("cracked_mossy_deepslate_tile_stairs", new StairsBlock(CRACKED_MOSSY_DEEPSLATE_TILES.getDefaultState(), AbstractBlock.Settings.copy(CRACKED_MOSSY_DEEPSLATE_TILES)));
	public static final Block CRACKED_MOSSY_DEEPSLATE_TILE_WALL = register("cracked_mossy_deepslate_tile_wall", new WallBlock(AbstractBlock.Settings.copy(CRACKED_MOSSY_DEEPSLATE_TILES).solid()));
	
	public static final Block MOSSY_TUFF = register("mossy_tuff", new Block(AbstractBlock.Settings.copy(Blocks.TUFF)));
	public static final Block MOSSY_TUFF_SLAB = register("mossy_tuff_slab", new SlabBlock(AbstractBlock.Settings.copy(MOSSY_TUFF)));
	public static final Block MOSSY_TUFF_STAIRS = register("mossy_tuff_stairs", new StairsBlock(MOSSY_TUFF.getDefaultState(), AbstractBlock.Settings.copy(MOSSY_TUFF)));
	public static final Block MOSSY_TUFF_WALL = register("mossy_tuff_wall", new WallBlock(AbstractBlock.Settings.copy(MOSSY_TUFF).solid()));
	public static final Block CRACKED_TUFF_BRICKS = register("cracked_tuff_bricks", new Block(AbstractBlock.Settings.copy(Blocks.TUFF_BRICKS)));
	public static final Block CRACKED_TUFF_BRICK_SLAB = register("cracked_tuff_brick_slab", new SlabBlock(AbstractBlock.Settings.copy(CRACKED_TUFF_BRICKS)));
	public static final Block CRACKED_TUFF_BRICK_STAIRS = register("cracked_tuff_brick_stairs", new StairsBlock(CRACKED_TUFF_BRICKS.getDefaultState(), AbstractBlock.Settings.copy(CRACKED_TUFF_BRICKS)));
	public static final Block CRACKED_TUFF_BRICK_WALL = register("cracked_tuff_brick_wall", new WallBlock(AbstractBlock.Settings.copy(CRACKED_TUFF_BRICKS).solid()));
	public static final Block MOSSY_TUFF_BRICKS = register("mossy_tuff_bricks", new Block(AbstractBlock.Settings.copy(Blocks.TUFF_BRICKS)));
	public static final Block MOSSY_TUFF_BRICK_SLAB = register("mossy_tuff_brick_slab", new SlabBlock(AbstractBlock.Settings.copy(MOSSY_TUFF_BRICKS)));
	public static final Block MOSSY_TUFF_BRICK_STAIRS = register("mossy_tuff_brick_stairs", new StairsBlock(MOSSY_TUFF_BRICKS.getDefaultState(), AbstractBlock.Settings.copy(MOSSY_TUFF_BRICKS)));
	public static final Block MOSSY_TUFF_BRICK_WALL = register("mossy_tuff_brick_wall", new WallBlock(AbstractBlock.Settings.copy(MOSSY_TUFF_BRICKS).solid()));
	public static final Block CRACKED_MOSSY_TUFF_BRICKS = register("cracked_mossy_tuff_bricks", new Block(AbstractBlock.Settings.copy(Blocks.TUFF_BRICKS)));
	public static final Block CRACKED_MOSSY_TUFF_BRICK_SLAB = register("cracked_mossy_tuff_brick_slab", new SlabBlock(AbstractBlock.Settings.copy(CRACKED_MOSSY_TUFF_BRICKS)));
	public static final Block CRACKED_MOSSY_TUFF_BRICK_STAIRS = register("cracked_mossy_tuff_brick_stairs", new StairsBlock(CRACKED_MOSSY_TUFF_BRICKS.getDefaultState(), AbstractBlock.Settings.copy(CRACKED_MOSSY_TUFF_BRICKS)));
	public static final Block CRACKED_MOSSY_TUFF_BRICK_WALL = register("cracked_mossy_tuff_brick_wall", new WallBlock(AbstractBlock.Settings.copy(CRACKED_MOSSY_TUFF_BRICKS).solid()));
	public static final Block CRACKED_CHISELED_TUFF_BRICKS = register("cracked_chiseled_tuff_bricks", new Block(AbstractBlock.Settings.copy(Blocks.CHISELED_TUFF_BRICKS)));
	public static final Block CRACKED_CHISELED_TUFF_BRICK_SLAB = register("cracked_chiseled_tuff_brick_slab", new SlabBlock(AbstractBlock.Settings.copy(CRACKED_CHISELED_TUFF_BRICKS)));
	public static final Block CRACKED_CHISELED_TUFF_BRICK_STAIRS = register("cracked_chiseled_tuff_brick_stairs", new StairsBlock(CRACKED_CHISELED_TUFF_BRICKS.getDefaultState(), AbstractBlock.Settings.copy(CRACKED_CHISELED_TUFF_BRICKS)));
	public static final Block CRACKED_CHISELED_TUFF_BRICK_WALL = register("cracked_chiseled_tuff_brick_wall", new WallBlock(AbstractBlock.Settings.copy(CRACKED_CHISELED_TUFF_BRICKS).solid()));
	public static final Block MOSSY_CHISELED_TUFF_BRICKS = register("mossy_chiseled_tuff_bricks", new Block(AbstractBlock.Settings.copy(Blocks.CHISELED_TUFF_BRICKS)));
	public static final Block MOSSY_CHISELED_TUFF_BRICK_SLAB = register("mossy_chiseled_tuff_brick_slab", new SlabBlock(AbstractBlock.Settings.copy(MOSSY_CHISELED_TUFF_BRICKS)));
	public static final Block MOSSY_CHISELED_TUFF_BRICK_STAIRS = register("mossy_chiseled_tuff_brick_stairs", new StairsBlock(MOSSY_CHISELED_TUFF_BRICKS.getDefaultState(), AbstractBlock.Settings.copy(MOSSY_CHISELED_TUFF_BRICKS)));
	public static final Block MOSSY_CHISELED_TUFF_BRICK_WALL = register("mossy_chiseled_tuff_brick_wall", new WallBlock(AbstractBlock.Settings.copy(MOSSY_CHISELED_TUFF_BRICKS).solid()));
	public static final Block CRACKED_MOSSY_CHISELED_TUFF_BRICKS = register("cracked_mossy_chiseled_tuff_bricks", new Block(AbstractBlock.Settings.copy(Blocks.CHISELED_TUFF_BRICKS)));
	public static final Block CRACKED_MOSSY_CHISELED_TUFF_BRICK_SLAB = register("cracked_mossy_chiseled_tuff_brick_slab", new SlabBlock(AbstractBlock.Settings.copy(CRACKED_MOSSY_CHISELED_TUFF_BRICKS)));
	public static final Block CRACKED_MOSSY_CHISELED_TUFF_BRICK_STAIRS = register("cracked_mossy_chiseled_tuff_brick_stairs", new StairsBlock(CRACKED_MOSSY_CHISELED_TUFF_BRICKS.getDefaultState(), AbstractBlock.Settings.copy(CRACKED_MOSSY_CHISELED_TUFF_BRICKS)));
	public static final Block CRACKED_MOSSY_CHISELED_TUFF_BRICK_WALL = register("cracked_mossy_chiseled_tuff_brick_wall", new WallBlock(AbstractBlock.Settings.copy(CRACKED_MOSSY_CHISELED_TUFF_BRICKS).solid()));
	
	public static final Block CRACKED_BRICKS = register("cracked_bricks", new Block(AbstractBlock.Settings.copy(Blocks.BRICKS)));
	public static final Block CRACKED_BRICK_SLAB = register("cracked_brick_slab", new SlabBlock(AbstractBlock.Settings.copy(CRACKED_BRICKS)));
	public static final Block CRACKED_BRICK_STAIRS = register("cracked_brick_stairs", new StairsBlock(CRACKED_BRICKS.getDefaultState(), AbstractBlock.Settings.copy(CRACKED_BRICKS)));
	public static final Block CRACKED_BRICK_WALL = register("cracked_brick_wall", new WallBlock(AbstractBlock.Settings.copy(CRACKED_BRICKS).solid()));
	public static final Block MOSSY_BRICKS = register("mossy_bricks", new Block(AbstractBlock.Settings.copy(Blocks.BRICKS)));
	public static final Block MOSSY_BRICK_SLAB = register("mossy_brick_slab", new SlabBlock(AbstractBlock.Settings.copy(MOSSY_BRICKS)));
	public static final Block MOSSY_BRICK_STAIRS = register("mossy_brick_stairs", new StairsBlock(MOSSY_BRICKS.getDefaultState(), AbstractBlock.Settings.copy(MOSSY_BRICKS)));
	public static final Block MOSSY_BRICK_WALL = register("mossy_brick_wall", new WallBlock(AbstractBlock.Settings.copy(MOSSY_BRICKS).solid()));
	public static final Block CRACKED_MOSSY_BRICKS = register("cracked_mossy_bricks", new Block(AbstractBlock.Settings.copy(Blocks.BRICKS)));
	public static final Block CRACKED_MOSSY_BRICK_SLAB = register("cracked_mossy_brick_slab", new SlabBlock(AbstractBlock.Settings.copy(CRACKED_MOSSY_BRICKS)));
	public static final Block CRACKED_MOSSY_BRICK_STAIRS = register("cracked_mossy_brick_stairs", new StairsBlock(CRACKED_MOSSY_BRICKS.getDefaultState(), AbstractBlock.Settings.copy(CRACKED_MOSSY_BRICKS)));
	public static final Block CRACKED_MOSSY_BRICK_WALL = register("cracked_mossy_brick_wall", new WallBlock(AbstractBlock.Settings.copy(CRACKED_MOSSY_BRICKS).solid()));
	
	public static final Block CRACKED_MUD_BRICKS = register("cracked_mud_bricks", new Block(AbstractBlock.Settings.copy(Blocks.MUD_BRICKS)));
	public static final Block CRACKED_MUD_BRICK_SLAB = register("cracked_mud_brick_slab", new SlabBlock(AbstractBlock.Settings.copy(CRACKED_MUD_BRICKS)));
	public static final Block CRACKED_MUD_BRICK_STAIRS = register("cracked_mud_brick_stairs", new StairsBlock(CRACKED_MUD_BRICKS.getDefaultState(), AbstractBlock.Settings.copy(CRACKED_MUD_BRICKS)));
	public static final Block CRACKED_MUD_BRICK_WALL = register("cracked_mud_brick_wall", new WallBlock(AbstractBlock.Settings.copy(CRACKED_MUD_BRICKS).solid()));
	public static final Block MOSSY_MUD_BRICKS = register("mossy_mud_bricks", new Block(AbstractBlock.Settings.copy(Blocks.MUD_BRICKS)));
	public static final Block MOSSY_MUD_BRICK_SLAB = register("mossy_mud_brick_slab", new SlabBlock(AbstractBlock.Settings.copy(MOSSY_MUD_BRICKS)));
	public static final Block MOSSY_MUD_BRICK_STAIRS = register("mossy_mud_brick_stairs", new StairsBlock(MOSSY_MUD_BRICKS.getDefaultState(), AbstractBlock.Settings.copy(MOSSY_MUD_BRICKS)));
	public static final Block MOSSY_MUD_BRICK_WALL = register("mossy_mud_brick_wall", new WallBlock(AbstractBlock.Settings.copy(MOSSY_MUD_BRICKS).solid()));
	public static final Block CRACKED_MOSSY_MUD_BRICKS = register("cracked_mossy_mud_bricks", new Block(AbstractBlock.Settings.copy(Blocks.MUD_BRICKS)));
	public static final Block CRACKED_MOSSY_MUD_BRICK_SLAB = register("cracked_mossy_mud_brick_slab", new SlabBlock(AbstractBlock.Settings.copy(CRACKED_MOSSY_MUD_BRICKS)));
	public static final Block CRACKED_MOSSY_MUD_BRICK_STAIRS = register("cracked_mossy_mud_brick_stairs", new StairsBlock(CRACKED_MOSSY_MUD_BRICKS.getDefaultState(), AbstractBlock.Settings.copy(CRACKED_MOSSY_MUD_BRICKS)));
	public static final Block CRACKED_MOSSY_MUD_BRICK_WALL = register("cracked_mossy_mud_brick_wall", new WallBlock(AbstractBlock.Settings.copy(CRACKED_MOSSY_MUD_BRICKS).solid()));
	
	public static final Block SANDSTONE_BRICKS = register("sandstone_bricks", new Block(AbstractBlock.Settings.create().mapColor(MapColor.PALE_YELLOW).instrument(NoteBlockInstrument.BASEDRUM).requiresTool().strength(0.8f)));
	public static final Block SANDSTONE_BRICK_SLAB = register("sandstone_brick_slab", new SlabBlock(AbstractBlock.Settings.copy(SANDSTONE_BRICKS)));
	public static final Block SANDSTONE_BRICK_STAIRS = register("sandstone_brick_stairs", new StairsBlock(SANDSTONE_BRICKS.getDefaultState(), AbstractBlock.Settings.copy(SANDSTONE_BRICKS)));
	public static final Block SANDSTONE_BRICK_WALL = register("sandstone_brick_wall", new WallBlock(AbstractBlock.Settings.copy(SANDSTONE_BRICKS).solid()));
	public static final Block CRACKED_SANDSTONE_BRICKS = register("cracked_sandstone_bricks", new Block(AbstractBlock.Settings.copy(SANDSTONE_BRICKS)));
	public static final Block CRACKED_SANDSTONE_BRICK_SLAB = register("cracked_sandstone_brick_slab", new SlabBlock(AbstractBlock.Settings.copy(CRACKED_SANDSTONE_BRICKS)));
	public static final Block CRACKED_SANDSTONE_BRICK_STAIRS = register("cracked_sandstone_brick_stairs", new StairsBlock(CRACKED_SANDSTONE_BRICKS.getDefaultState(), AbstractBlock.Settings.copy(CRACKED_SANDSTONE_BRICKS)));
	public static final Block CRACKED_SANDSTONE_BRICK_WALL = register("cracked_sandstone_brick_wall", new WallBlock(AbstractBlock.Settings.copy(CRACKED_SANDSTONE_BRICKS).solid()));
	public static final Block MOSSY_SANDSTONE_BRICKS = register("mossy_sandstone_bricks", new Block(AbstractBlock.Settings.copy(SANDSTONE_BRICKS)));
	public static final Block MOSSY_SANDSTONE_BRICK_SLAB = register("mossy_sandstone_brick_slab", new SlabBlock(AbstractBlock.Settings.copy(MOSSY_SANDSTONE_BRICKS)));
	public static final Block MOSSY_SANDSTONE_BRICK_STAIRS = register("mossy_sandstone_brick_stairs", new StairsBlock(MOSSY_SANDSTONE_BRICKS.getDefaultState(), AbstractBlock.Settings.copy(MOSSY_SANDSTONE_BRICKS)));
	public static final Block MOSSY_SANDSTONE_BRICK_WALL = register("mossy_sandstone_brick_wall", new WallBlock(AbstractBlock.Settings.copy(MOSSY_SANDSTONE_BRICKS).solid()));
	public static final Block CRACKED_MOSSY_SANDSTONE_BRICKS = register("cracked_mossy_sandstone_bricks", new Block(AbstractBlock.Settings.copy(SANDSTONE_BRICKS)));
	public static final Block CRACKED_MOSSY_SANDSTONE_BRICK_SLAB = register("cracked_mossy_sandstone_brick_slab", new SlabBlock(AbstractBlock.Settings.copy(CRACKED_MOSSY_SANDSTONE_BRICKS)));
	public static final Block CRACKED_MOSSY_SANDSTONE_BRICK_STAIRS = register("cracked_mossy_sandstone_brick_stairs", new StairsBlock(CRACKED_MOSSY_SANDSTONE_BRICKS.getDefaultState(), AbstractBlock.Settings.copy(CRACKED_MOSSY_SANDSTONE_BRICKS)));
	public static final Block CRACKED_MOSSY_SANDSTONE_BRICK_WALL = register("cracked_mossy_sandstone_brick_wall", new WallBlock(AbstractBlock.Settings.copy(CRACKED_MOSSY_SANDSTONE_BRICKS).solid()));
	
	public static final Block RED_SANDSTONE_BRICKS = register("red_sandstone_bricks", new Block(AbstractBlock.Settings.create().mapColor(MapColor.ORANGE).instrument(NoteBlockInstrument.BASEDRUM).requiresTool().strength(0.8f)));
	public static final Block RED_SANDSTONE_BRICK_SLAB = register("red_sandstone_brick_slab", new SlabBlock(AbstractBlock.Settings.copy(RED_SANDSTONE_BRICKS)));
	public static final Block RED_SANDSTONE_BRICK_STAIRS = register("red_sandstone_brick_stairs", new StairsBlock(RED_SANDSTONE_BRICKS.getDefaultState(), AbstractBlock.Settings.copy(RED_SANDSTONE_BRICKS)));
	public static final Block RED_SANDSTONE_BRICK_WALL = register("red_sandstone_brick_wall", new WallBlock(AbstractBlock.Settings.copy(RED_SANDSTONE_BRICKS).solid()));
	public static final Block CRACKED_RED_SANDSTONE_BRICKS = register("cracked_red_sandstone_bricks", new Block(AbstractBlock.Settings.copy(RED_SANDSTONE_BRICKS)));
	public static final Block CRACKED_RED_SANDSTONE_BRICK_SLAB = register("cracked_red_sandstone_brick_slab", new SlabBlock(AbstractBlock.Settings.copy(CRACKED_RED_SANDSTONE_BRICKS)));
	public static final Block CRACKED_RED_SANDSTONE_BRICK_STAIRS = register("cracked_red_sandstone_brick_stairs", new StairsBlock(CRACKED_RED_SANDSTONE_BRICKS.getDefaultState(), AbstractBlock.Settings.copy(CRACKED_RED_SANDSTONE_BRICKS)));
	public static final Block CRACKED_RED_SANDSTONE_BRICK_WALL = register("cracked_red_sandstone_brick_wall", new WallBlock(AbstractBlock.Settings.copy(CRACKED_RED_SANDSTONE_BRICKS).solid()));
	public static final Block MOSSY_RED_SANDSTONE_BRICKS = register("mossy_red_sandstone_bricks", new Block(AbstractBlock.Settings.copy(RED_SANDSTONE_BRICKS)));
	public static final Block MOSSY_RED_SANDSTONE_BRICK_SLAB = register("mossy_red_sandstone_brick_slab", new SlabBlock(AbstractBlock.Settings.copy(MOSSY_RED_SANDSTONE_BRICKS)));
	public static final Block MOSSY_RED_SANDSTONE_BRICK_STAIRS = register("mossy_red_sandstone_brick_stairs", new StairsBlock(MOSSY_RED_SANDSTONE_BRICKS.getDefaultState(), AbstractBlock.Settings.copy(MOSSY_RED_SANDSTONE_BRICKS)));
	public static final Block MOSSY_RED_SANDSTONE_BRICK_WALL = register("mossy_red_sandstone_brick_wall", new WallBlock(AbstractBlock.Settings.copy(MOSSY_RED_SANDSTONE_BRICKS).solid()));
	public static final Block CRACKED_MOSSY_RED_SANDSTONE_BRICKS = register("cracked_mossy_red_sandstone_bricks", new Block(AbstractBlock.Settings.copy(RED_SANDSTONE_BRICKS)));
	public static final Block CRACKED_MOSSY_RED_SANDSTONE_BRICK_SLAB = register("cracked_mossy_red_sandstone_brick_slab", new SlabBlock(AbstractBlock.Settings.copy(CRACKED_MOSSY_RED_SANDSTONE_BRICKS)));
	public static final Block CRACKED_MOSSY_RED_SANDSTONE_BRICK_STAIRS = register("cracked_mossy_red_sandstone_brick_stairs", new StairsBlock(CRACKED_MOSSY_RED_SANDSTONE_BRICKS.getDefaultState(), AbstractBlock.Settings.copy(CRACKED_MOSSY_RED_SANDSTONE_BRICKS)));
	public static final Block CRACKED_MOSSY_RED_SANDSTONE_BRICK_WALL = register("cracked_mossy_red_sandstone_brick_wall", new WallBlock(AbstractBlock.Settings.copy(CRACKED_MOSSY_RED_SANDSTONE_BRICKS).solid()));
	
	public static final Block CRACKED_PRISMARINE_BRICKS = register("cracked_prismarine_bricks", new Block(AbstractBlock.Settings.copy(Blocks.PRISMARINE_BRICKS)));
	public static final Block CRACKED_PRISMARINE_BRICK_SLAB = register("cracked_prismarine_brick_slab", new SlabBlock(AbstractBlock.Settings.copy(CRACKED_PRISMARINE_BRICKS)));
	public static final Block CRACKED_PRISMARINE_BRICK_STAIRS = register("cracked_prismarine_brick_stairs", new StairsBlock(CRACKED_PRISMARINE_BRICKS.getDefaultState(), AbstractBlock.Settings.copy(CRACKED_PRISMARINE_BRICKS)));
	public static final Block CRACKED_PRISMARINE_BRICK_WALL = register("cracked_prismarine_brick_wall", new WallBlock(AbstractBlock.Settings.copy(CRACKED_PRISMARINE_BRICKS).solid()));
	
	public static final Block SOUL_SANDSTONE = register("soul_sandstone", new Block(AbstractBlock.Settings.create().mapColor(MapColor.BROWN).instrument(NoteBlockInstrument.BASEDRUM).requiresTool().strength(0.8f).velocityMultiplier(0.4f).sounds(BlockSoundGroup.NETHERRACK)));
	public static final Block SOUL_SANDSTONE_SLAB = register("soul_sandstone_slab", new SlabBlock(AbstractBlock.Settings.copy(SOUL_SANDSTONE)));
	public static final Block SOUL_SANDSTONE_STAIRS = register("soul_sandstone_stairs", new StairsBlock(SOUL_SANDSTONE.getDefaultState(), AbstractBlock.Settings.copy(SOUL_SANDSTONE)));
	public static final Block SOUL_SANDSTONE_WALL = register("soul_sandstone_wall", new WallBlock(AbstractBlock.Settings.copy(SOUL_SANDSTONE).solid()));
	public static final Block CHISELED_SOUL_SANDSTONE = register("chiseled_soul_sandstone", new Block(AbstractBlock.Settings.copy(SOUL_SANDSTONE)));
	public static final Block CHISELED_SOUL_SANDSTONE_SLAB = register("chiseled_soul_sandstone_slab", new SlabBlock(AbstractBlock.Settings.copy(CHISELED_SOUL_SANDSTONE)));
	public static final Block CHISELED_SOUL_SANDSTONE_STAIRS = register("chiseled_soul_sandstone_stairs", new StairsBlock(CHISELED_SOUL_SANDSTONE.getDefaultState(), AbstractBlock.Settings.copy(CHISELED_SOUL_SANDSTONE)));
	public static final Block CHISELED_SOUL_SANDSTONE_WALL = register("chiseled_soul_sandstone_wall", new WallBlock(AbstractBlock.Settings.copy(CHISELED_SOUL_SANDSTONE).solid()));
	public static final Block SMOOTH_SOUL_SANDSTONE = register("smooth_soul_sandstone", new Block(AbstractBlock.Settings.copy(SOUL_SANDSTONE)));
	public static final Block SMOOTH_SOUL_SANDSTONE_SLAB = register("smooth_soul_sandstone_slab", new SlabBlock(AbstractBlock.Settings.copy(SMOOTH_SOUL_SANDSTONE)));
	public static final Block SMOOTH_SOUL_SANDSTONE_STAIRS = register("smooth_soul_sandstone_stairs", new StairsBlock(SMOOTH_SOUL_SANDSTONE.getDefaultState(), AbstractBlock.Settings.copy(SMOOTH_SOUL_SANDSTONE)));
	public static final Block SMOOTH_SOUL_SANDSTONE_WALL = register("smooth_soul_sandstone_wall", new WallBlock(AbstractBlock.Settings.copy(SMOOTH_SOUL_SANDSTONE).solid()));
	public static final Block CUT_SOUL_SANDSTONE = register("cut_soul_sandstone", new Block(AbstractBlock.Settings.copy(SOUL_SANDSTONE)));
	public static final Block CUT_SOUL_SANDSTONE_SLAB = register("cut_soul_sandstone_slab", new SlabBlock(AbstractBlock.Settings.copy(CUT_SOUL_SANDSTONE)));
	public static final Block CUT_SOUL_SANDSTONE_STAIRS = register("cut_soul_sandstone_stairs", new StairsBlock(CUT_SOUL_SANDSTONE.getDefaultState(), AbstractBlock.Settings.copy(CUT_SOUL_SANDSTONE)));
	public static final Block CUT_SOUL_SANDSTONE_WALL = register("cut_soul_sandstone_wall", new WallBlock(AbstractBlock.Settings.copy(CUT_SOUL_SANDSTONE).solid()));
	public static final Block SOUL_SANDSTONE_BRICKS = register("soul_sandstone_bricks", new Block(AbstractBlock.Settings.copy(SOUL_SANDSTONE)));
	public static final Block SOUL_SANDSTONE_BRICK_SLAB = register("soul_sandstone_brick_slab", new SlabBlock(AbstractBlock.Settings.copy(SOUL_SANDSTONE_BRICKS)));
	public static final Block SOUL_SANDSTONE_BRICK_STAIRS = register("soul_sandstone_brick_stairs", new StairsBlock(SOUL_SANDSTONE_BRICKS.getDefaultState(), AbstractBlock.Settings.copy(SOUL_SANDSTONE_BRICKS)));
	public static final Block SOUL_SANDSTONE_BRICK_WALL = register("soul_sandstone_brick_wall", new WallBlock(AbstractBlock.Settings.copy(SOUL_SANDSTONE_BRICKS).solid()));
	public static final Block CRACKED_SOUL_SANDSTONE_BRICKS = register("cracked_soul_sandstone_bricks", new Block(AbstractBlock.Settings.copy(SOUL_SANDSTONE_BRICKS)));
	public static final Block CRACKED_SOUL_SANDSTONE_BRICK_SLAB = register("cracked_soul_sandstone_brick_slab", new SlabBlock(AbstractBlock.Settings.copy(CRACKED_SOUL_SANDSTONE_BRICKS)));
	public static final Block CRACKED_SOUL_SANDSTONE_BRICK_STAIRS = register("cracked_soul_sandstone_brick_stairs", new StairsBlock(CRACKED_SOUL_SANDSTONE_BRICKS.getDefaultState(), AbstractBlock.Settings.copy(CRACKED_SOUL_SANDSTONE_BRICKS)));
	public static final Block CRACKED_SOUL_SANDSTONE_BRICK_WALL = register("cracked_soul_sandstone_brick_wall", new WallBlock(AbstractBlock.Settings.copy(CRACKED_SOUL_SANDSTONE_BRICKS).solid()));
	public static final Block MOSSY_SOUL_SANDSTONE_BRICKS = register("mossy_soul_sandstone_bricks", new Block(AbstractBlock.Settings.copy(SOUL_SANDSTONE_BRICKS)));
	public static final Block MOSSY_SOUL_SANDSTONE_BRICK_SLAB = register("mossy_soul_sandstone_brick_slab", new SlabBlock(AbstractBlock.Settings.copy(MOSSY_SOUL_SANDSTONE_BRICKS)));
	public static final Block MOSSY_SOUL_SANDSTONE_BRICK_STAIRS = register("mossy_soul_sandstone_brick_stairs", new StairsBlock(MOSSY_SOUL_SANDSTONE_BRICKS.getDefaultState(), AbstractBlock.Settings.copy(MOSSY_SOUL_SANDSTONE_BRICKS)));
	public static final Block MOSSY_SOUL_SANDSTONE_BRICK_WALL = register("mossy_soul_sandstone_brick_wall", new WallBlock(AbstractBlock.Settings.copy(MOSSY_SOUL_SANDSTONE_BRICKS).solid()));
	public static final Block CRACKED_MOSSY_SOUL_SANDSTONE_BRICKS = register("cracked_mossy_soul_sandstone_bricks", new Block(AbstractBlock.Settings.copy(SOUL_SANDSTONE_BRICKS)));
	public static final Block CRACKED_MOSSY_SOUL_SANDSTONE_BRICK_SLAB = register("cracked_mossy_soul_sandstone_brick_slab", new SlabBlock(AbstractBlock.Settings.copy(CRACKED_MOSSY_SOUL_SANDSTONE_BRICKS)));
	public static final Block CRACKED_MOSSY_SOUL_SANDSTONE_BRICK_STAIRS = register("cracked_mossy_soul_sandstone_brick_stairs", new StairsBlock(CRACKED_MOSSY_SOUL_SANDSTONE_BRICKS.getDefaultState(), AbstractBlock.Settings.copy(CRACKED_MOSSY_SOUL_SANDSTONE_BRICKS)));
	public static final Block CRACKED_MOSSY_SOUL_SANDSTONE_BRICK_WALL = register("cracked_mossy_soul_sandstone_brick_wall", new WallBlock(AbstractBlock.Settings.copy(CRACKED_MOSSY_SOUL_SANDSTONE_BRICKS).solid()));
	
	public static final Block WITHER_BONE_BLOCK = register("wither_bone_block", new PillarBlock(AbstractBlock.Settings.create().mapColor(MapColor.BLACK).instrument(NoteBlockInstrument.XYLOPHONE).requiresTool().strength(2.0f).sounds(BlockSoundGroup.BONE)));
	public static final Block WITHER_BONE_SLAB = register("wither_bone_slab", new OrientableSlabBlock(AbstractBlock.Settings.copy(WITHER_BONE_BLOCK)));
	public static final Block WITHER_BONE_STAIRS = register("wither_bone_stairs", new OrientableStairsBlock(WITHER_BONE_BLOCK.getDefaultState(), AbstractBlock.Settings.copy(WITHER_BONE_BLOCK)));
	public static final Block WITHER_BONE_WALL = register("wither_bone_wall", new WallBlock(AbstractBlock.Settings.copy(WITHER_BONE_BLOCK).solid()));
	
	public static final Block WARPED_WART = register("warped_wart", new WarpedWartBlock(AbstractBlock.Settings.create().mapColor(MapColor.BRIGHT_TEAL).noCollision().ticksRandomly().sounds(BlockSoundGroup.NETHER_WART).pistonBehavior(PistonBehavior.DESTROY)));
	
	public static final Block CRACKED_CHISELED_NETHER_BRICKS = register("cracked_chiseled_nether_bricks", new Block(AbstractBlock.Settings.copy(Blocks.CHISELED_NETHER_BRICKS)));
	public static final Block CRACKED_CHISELED_NETHER_BRICK_SLAB = register("cracked_chiseled_nether_brick_slab", new SlabBlock(AbstractBlock.Settings.copy(CRACKED_CHISELED_NETHER_BRICKS)));
	public static final Block CRACKED_CHISELED_NETHER_BRICK_STAIRS = register("cracked_chiseled_nether_brick_stairs", new StairsBlock(CRACKED_CHISELED_NETHER_BRICKS.getDefaultState(), AbstractBlock.Settings.copy(CRACKED_CHISELED_NETHER_BRICKS)));
	public static final Block CRACKED_CHISELED_NETHER_BRICK_WALL = register("cracked_chiseled_nether_brick_wall", new WallBlock(AbstractBlock.Settings.copy(CRACKED_CHISELED_NETHER_BRICKS).solid()));
	
	public static final Block CRACKED_RED_NETHER_BRICKS = register("cracked_red_nether_bricks", new Block(AbstractBlock.Settings.copy(Blocks.RED_NETHER_BRICKS)));
	public static final Block CRACKED_RED_NETHER_BRICK_SLAB = register("cracked_red_nether_brick_slab", new SlabBlock(AbstractBlock.Settings.copy(CRACKED_RED_NETHER_BRICKS)));
	public static final Block CRACKED_RED_NETHER_BRICK_STAIRS = register("cracked_red_nether_brick_stairs", new StairsBlock(CRACKED_RED_NETHER_BRICKS.getDefaultState(), AbstractBlock.Settings.copy(CRACKED_RED_NETHER_BRICKS)));
	public static final Block CRACKED_RED_NETHER_BRICK_WALL = register("cracked_red_nether_brick_wall", new WallBlock(AbstractBlock.Settings.copy(CRACKED_RED_NETHER_BRICKS).solid()));
	public static final Block CRACKED_RED_NETHER_BRICK_FENCE = register("cracked_red_nether_brick_fence", new FenceBlock(AbstractBlock.Settings.copy(CRACKED_RED_NETHER_BRICKS).solid()));
	public static final Block CRACKED_RED_NETHER_BRICK_FENCE_GATE = register("cracked_red_nether_brick_fence_gate", new FenceGateBlock(SSWPWoodTypes.NETHER_BRICK, AbstractBlock.Settings.copy(CRACKED_RED_NETHER_BRICKS).solid()));
	public static final Block CHISELED_RED_NETHER_BRICKS = register("chiseled_red_nether_bricks", new Block(AbstractBlock.Settings.copy(Blocks.RED_NETHER_BRICKS)));
	public static final Block CHISELED_RED_NETHER_BRICK_SLAB = register("chiseled_red_nether_brick_slab", new SlabBlock(AbstractBlock.Settings.copy(CHISELED_RED_NETHER_BRICKS)));
	public static final Block CHISELED_RED_NETHER_BRICK_STAIRS = register("chiseled_red_nether_brick_stairs", new StairsBlock(CHISELED_RED_NETHER_BRICKS.getDefaultState(), AbstractBlock.Settings.copy(CHISELED_RED_NETHER_BRICKS)));
	public static final Block CHISELED_RED_NETHER_BRICK_WALL = register("chiseled_red_nether_brick_wall", new WallBlock(AbstractBlock.Settings.copy(CHISELED_RED_NETHER_BRICKS).solid()));
	public static final Block CRACKED_CHISELED_RED_NETHER_BRICKS = register("cracked_chiseled_red_nether_bricks", new Block(AbstractBlock.Settings.copy(CHISELED_RED_NETHER_BRICKS)));
	public static final Block CRACKED_CHISELED_RED_NETHER_BRICK_SLAB = register("cracked_chiseled_red_nether_brick_slab", new SlabBlock(AbstractBlock.Settings.copy(CRACKED_CHISELED_RED_NETHER_BRICKS)));
	public static final Block CRACKED_CHISELED_RED_NETHER_BRICK_STAIRS = register("cracked_chiseled_red_nether_brick_stairs", new StairsBlock(CRACKED_CHISELED_RED_NETHER_BRICKS.getDefaultState(), AbstractBlock.Settings.copy(CRACKED_CHISELED_RED_NETHER_BRICKS)));
	public static final Block CRACKED_CHISELED_RED_NETHER_BRICK_WALL = register("cracked_chiseled_red_nether_brick_wall", new WallBlock(AbstractBlock.Settings.copy(CRACKED_CHISELED_RED_NETHER_BRICKS).solid()));
	
	public static final Block WARPED_NETHER_BRICKS = register("warped_nether_bricks", new Block(AbstractBlock.Settings.create().mapColor(MapColor.BRIGHT_TEAL).instrument(NoteBlockInstrument.BASEDRUM).requiresTool().strength(2.0f, 6.0f).sounds(BlockSoundGroup.NETHER_BRICKS).luminance(state -> 1)));
	public static final Block WARPED_NETHER_BRICK_SLAB = register("warped_nether_brick_slab", new SlabBlock(AbstractBlock.Settings.copy(WARPED_NETHER_BRICKS)));
	public static final Block WARPED_NETHER_BRICK_STAIRS = register("warped_nether_brick_stairs", new StairsBlock(WARPED_NETHER_BRICKS.getDefaultState(), AbstractBlock.Settings.copy(WARPED_NETHER_BRICKS)));
	public static final Block WARPED_NETHER_BRICK_WALL = register("warped_nether_brick_wall", new WallBlock(AbstractBlock.Settings.copy(WARPED_NETHER_BRICKS).solid()));
	public static final Block WARPED_NETHER_BRICK_FENCE = register("warped_nether_brick_fence", new FenceBlock(AbstractBlock.Settings.copy(WARPED_NETHER_BRICKS).solid()));
	public static final Block WARPED_NETHER_BRICK_FENCE_GATE = register("warped_nether_brick_fence_gate", new FenceGateBlock(SSWPWoodTypes.NETHER_BRICK, AbstractBlock.Settings.copy(WARPED_NETHER_BRICKS).solid()));
	public static final Block CRACKED_WARPED_NETHER_BRICKS = register("cracked_warped_nether_bricks", new Block(AbstractBlock.Settings.copy(WARPED_NETHER_BRICKS)));
	public static final Block CRACKED_WARPED_NETHER_BRICK_SLAB = register("cracked_warped_nether_brick_slab", new SlabBlock(AbstractBlock.Settings.copy(CRACKED_WARPED_NETHER_BRICKS)));
	public static final Block CRACKED_WARPED_NETHER_BRICK_STAIRS = register("cracked_warped_nether_brick_stairs", new StairsBlock(CRACKED_WARPED_NETHER_BRICKS.getDefaultState(), AbstractBlock.Settings.copy(CRACKED_WARPED_NETHER_BRICKS)));
	public static final Block CRACKED_WARPED_NETHER_BRICK_WALL = register("cracked_warped_nether_brick_wall", new WallBlock(AbstractBlock.Settings.copy(CRACKED_WARPED_NETHER_BRICKS).solid()));
	public static final Block CRACKED_WARPED_NETHER_BRICK_FENCE = register("cracked_warped_nether_brick_fence", new FenceBlock(AbstractBlock.Settings.copy(CRACKED_WARPED_NETHER_BRICKS).solid()));
	public static final Block CRACKED_WARPED_NETHER_BRICK_FENCE_GATE = register("cracked_warped_nether_brick_fence_gate", new FenceGateBlock(SSWPWoodTypes.NETHER_BRICK, AbstractBlock.Settings.copy(CRACKED_WARPED_NETHER_BRICKS).solid()));
	public static final Block CHISELED_WARPED_NETHER_BRICKS = register("chiseled_warped_nether_bricks", new Block(AbstractBlock.Settings.copy(WARPED_NETHER_BRICKS)));
	public static final Block CHISELED_WARPED_NETHER_BRICK_SLAB = register("chiseled_warped_nether_brick_slab", new SlabBlock(AbstractBlock.Settings.copy(CHISELED_WARPED_NETHER_BRICKS)));
	public static final Block CHISELED_WARPED_NETHER_BRICK_STAIRS = register("chiseled_warped_nether_brick_stairs", new StairsBlock(CHISELED_WARPED_NETHER_BRICKS.getDefaultState(), AbstractBlock.Settings.copy(CHISELED_WARPED_NETHER_BRICKS)));
	public static final Block CHISELED_WARPED_NETHER_BRICK_WALL = register("chiseled_warped_nether_brick_wall", new WallBlock(AbstractBlock.Settings.copy(CHISELED_WARPED_NETHER_BRICKS).solid()));
	public static final Block CRACKED_CHISELED_WARPED_NETHER_BRICKS = register("cracked_chiseled_warped_nether_bricks", new Block(AbstractBlock.Settings.copy(WARPED_NETHER_BRICKS)));
	public static final Block CRACKED_CHISELED_WARPED_NETHER_BRICK_SLAB = register("cracked_chiseled_warped_nether_brick_slab", new SlabBlock(AbstractBlock.Settings.copy(CRACKED_CHISELED_WARPED_NETHER_BRICKS)));
	public static final Block CRACKED_CHISELED_WARPED_NETHER_BRICK_STAIRS = register("cracked_chiseled_warped_nether_brick_stairs", new StairsBlock(CRACKED_CHISELED_WARPED_NETHER_BRICKS.getDefaultState(), AbstractBlock.Settings.copy(CRACKED_CHISELED_WARPED_NETHER_BRICKS)));
	public static final Block CRACKED_CHISELED_WARPED_NETHER_BRICK_WALL = register("cracked_chiseled_warped_nether_brick_wall", new WallBlock(AbstractBlock.Settings.copy(CRACKED_CHISELED_WARPED_NETHER_BRICKS).solid()));
	
	public static final Block WITHERED_NETHER_BRICKS = register("withered_nether_bricks", new Block(AbstractBlock.Settings.create().mapColor(MapColor.BLACK).instrument(NoteBlockInstrument.BASEDRUM).requiresTool().strength(2.0f, 6.0f).sounds(BlockSoundGroup.NETHER_BRICKS)));
	public static final Block WITHERED_NETHER_BRICK_SLAB = register("withered_nether_brick_slab", new SlabBlock(AbstractBlock.Settings.copy(WITHERED_NETHER_BRICKS)));
	public static final Block WITHERED_NETHER_BRICK_STAIRS = register("withered_nether_brick_stairs", new StairsBlock(WITHERED_NETHER_BRICKS.getDefaultState(), AbstractBlock.Settings.copy(WITHERED_NETHER_BRICKS)));
	public static final Block WITHERED_NETHER_BRICK_WALL = register("withered_nether_brick_wall", new WallBlock(AbstractBlock.Settings.copy(WITHERED_NETHER_BRICKS).solid()));
	public static final Block WITHERED_NETHER_BRICK_FENCE = register("withered_nether_brick_fence", new FenceBlock(AbstractBlock.Settings.copy(WITHERED_NETHER_BRICKS).solid()));
	public static final Block WITHERED_NETHER_BRICK_FENCE_GATE = register("withered_nether_brick_fence_gate", new FenceGateBlock(SSWPWoodTypes.NETHER_BRICK, AbstractBlock.Settings.copy(WITHERED_NETHER_BRICKS).solid()));
	public static final Block CRACKED_WITHERED_NETHER_BRICKS = register("cracked_withered_nether_bricks", new Block(AbstractBlock.Settings.copy(WITHERED_NETHER_BRICKS)));
	public static final Block CRACKED_WITHERED_NETHER_BRICK_SLAB = register("cracked_withered_nether_brick_slab", new SlabBlock(AbstractBlock.Settings.copy(CRACKED_WITHERED_NETHER_BRICKS)));
	public static final Block CRACKED_WITHERED_NETHER_BRICK_STAIRS = register("cracked_withered_nether_brick_stairs", new StairsBlock(CRACKED_WITHERED_NETHER_BRICKS.getDefaultState(), AbstractBlock.Settings.copy(CRACKED_WITHERED_NETHER_BRICKS)));
	public static final Block CRACKED_WITHERED_NETHER_BRICK_WALL = register("cracked_withered_nether_brick_wall", new WallBlock(AbstractBlock.Settings.copy(CRACKED_WITHERED_NETHER_BRICKS).solid()));
	public static final Block CRACKED_WITHERED_NETHER_BRICK_FENCE = register("cracked_withered_nether_brick_fence", new FenceBlock(AbstractBlock.Settings.copy(CRACKED_WITHERED_NETHER_BRICKS).solid()));
	public static final Block CRACKED_WITHERED_NETHER_BRICK_FENCE_GATE = register("cracked_withered_nether_brick_fence_gate", new FenceGateBlock(SSWPWoodTypes.NETHER_BRICK, AbstractBlock.Settings.copy(CRACKED_WITHERED_NETHER_BRICKS).solid()));
	public static final Block CHISELED_WITHERED_NETHER_BRICKS = register("chiseled_withered_nether_bricks", new Block(AbstractBlock.Settings.copy(WITHERED_NETHER_BRICKS)));
	public static final Block CHISELED_WITHERED_NETHER_BRICK_SLAB = register("chiseled_withered_nether_brick_slab", new SlabBlock(AbstractBlock.Settings.copy(CHISELED_WITHERED_NETHER_BRICKS)));
	public static final Block CHISELED_WITHERED_NETHER_BRICK_STAIRS = register("chiseled_withered_nether_brick_stairs", new StairsBlock(CHISELED_WITHERED_NETHER_BRICKS.getDefaultState(), AbstractBlock.Settings.copy(CHISELED_WITHERED_NETHER_BRICKS)));
	public static final Block CHISELED_WITHERED_NETHER_BRICK_WALL = register("chiseled_withered_nether_brick_wall", new WallBlock(AbstractBlock.Settings.copy(CHISELED_WITHERED_NETHER_BRICKS).solid()));
	public static final Block CRACKED_CHISELED_WITHERED_NETHER_BRICKS = register("cracked_chiseled_withered_nether_bricks", new Block(AbstractBlock.Settings.copy(WITHERED_NETHER_BRICKS)));
	public static final Block CRACKED_CHISELED_WITHERED_NETHER_BRICK_SLAB = register("cracked_chiseled_withered_nether_brick_slab", new SlabBlock(AbstractBlock.Settings.copy(CRACKED_CHISELED_WITHERED_NETHER_BRICKS)));
	public static final Block CRACKED_CHISELED_WITHERED_NETHER_BRICK_STAIRS = register("cracked_chiseled_withered_nether_brick_stairs", new StairsBlock(CRACKED_CHISELED_WITHERED_NETHER_BRICKS.getDefaultState(), AbstractBlock.Settings.copy(CRACKED_CHISELED_WITHERED_NETHER_BRICKS)));
	public static final Block CRACKED_CHISELED_WITHERED_NETHER_BRICK_WALL = register("cracked_chiseled_withered_nether_brick_wall", new WallBlock(AbstractBlock.Settings.copy(CRACKED_CHISELED_WITHERED_NETHER_BRICKS).solid()));
	
	public static final Block SOUL_NETHER_BRICKS = register("soul_nether_bricks", new Block(AbstractBlock.Settings.create().mapColor(MapColor.BROWN).instrument(NoteBlockInstrument.BASEDRUM).requiresTool().strength(2.0f, 6.0f).velocityMultiplier(0.4f).sounds(BlockSoundGroup.NETHER_BRICKS)));
	public static final Block SOUL_NETHER_BRICK_SLAB = register("soul_nether_brick_slab", new SlabBlock(AbstractBlock.Settings.copy(SOUL_NETHER_BRICKS)));
	public static final Block SOUL_NETHER_BRICK_STAIRS = register("soul_nether_brick_stairs", new StairsBlock(SOUL_NETHER_BRICKS.getDefaultState(), AbstractBlock.Settings.copy(SOUL_NETHER_BRICKS)));
	public static final Block SOUL_NETHER_BRICK_WALL = register("soul_nether_brick_wall", new WallBlock(AbstractBlock.Settings.copy(SOUL_NETHER_BRICKS).solid()));
	public static final Block SOUL_NETHER_BRICK_FENCE = register("soul_nether_brick_fence", new FenceBlock(AbstractBlock.Settings.copy(SOUL_NETHER_BRICKS).solid()));
	public static final Block SOUL_NETHER_BRICK_FENCE_GATE = register("soul_nether_brick_fence_gate", new FenceGateBlock(SSWPWoodTypes.NETHER_BRICK, AbstractBlock.Settings.copy(SOUL_NETHER_BRICKS).solid()));
	public static final Block CRACKED_SOUL_NETHER_BRICKS = register("cracked_soul_nether_bricks", new Block(AbstractBlock.Settings.copy(SOUL_NETHER_BRICKS)));
	public static final Block CRACKED_SOUL_NETHER_BRICK_SLAB = register("cracked_soul_nether_brick_slab", new SlabBlock(AbstractBlock.Settings.copy(CRACKED_SOUL_NETHER_BRICKS)));
	public static final Block CRACKED_SOUL_NETHER_BRICK_STAIRS = register("cracked_soul_nether_brick_stairs", new StairsBlock(CRACKED_SOUL_NETHER_BRICKS.getDefaultState(), AbstractBlock.Settings.copy(CRACKED_SOUL_NETHER_BRICKS)));
	public static final Block CRACKED_SOUL_NETHER_BRICK_WALL = register("cracked_soul_nether_brick_wall", new WallBlock(AbstractBlock.Settings.copy(CRACKED_SOUL_NETHER_BRICKS).solid()));
	public static final Block CRACKED_SOUL_NETHER_BRICK_FENCE = register("cracked_soul_nether_brick_fence", new FenceBlock(AbstractBlock.Settings.copy(CRACKED_SOUL_NETHER_BRICKS).solid()));
	public static final Block CRACKED_SOUL_NETHER_BRICK_FENCE_GATE = register("cracked_soul_nether_brick_fence_gate", new FenceGateBlock(SSWPWoodTypes.NETHER_BRICK, AbstractBlock.Settings.copy(CRACKED_SOUL_NETHER_BRICKS).solid()));
	public static final Block CHISELED_SOUL_NETHER_BRICKS = register("chiseled_soul_nether_bricks", new Block(AbstractBlock.Settings.copy(SOUL_NETHER_BRICKS)));
	public static final Block CHISELED_SOUL_NETHER_BRICK_SLAB = register("chiseled_soul_nether_brick_slab", new SlabBlock(AbstractBlock.Settings.copy(CHISELED_SOUL_NETHER_BRICKS)));
	public static final Block CHISELED_SOUL_NETHER_BRICK_STAIRS = register("chiseled_soul_nether_brick_stairs", new StairsBlock(CHISELED_SOUL_NETHER_BRICKS.getDefaultState(), AbstractBlock.Settings.copy(CHISELED_SOUL_NETHER_BRICKS)));
	public static final Block CHISELED_SOUL_NETHER_BRICK_WALL = register("chiseled_soul_nether_brick_wall", new WallBlock(AbstractBlock.Settings.copy(CHISELED_SOUL_NETHER_BRICKS).solid()));
	public static final Block CRACKED_CHISELED_SOUL_NETHER_BRICKS = register("cracked_chiseled_soul_nether_bricks", new Block(AbstractBlock.Settings.copy(SOUL_NETHER_BRICKS)));
	public static final Block CRACKED_CHISELED_SOUL_NETHER_BRICK_SLAB = register("cracked_chiseled_soul_nether_brick_slab", new SlabBlock(AbstractBlock.Settings.copy(CRACKED_CHISELED_SOUL_NETHER_BRICKS)));
	public static final Block CRACKED_CHISELED_SOUL_NETHER_BRICK_STAIRS = register("cracked_chiseled_soul_nether_brick_stairs", new StairsBlock(CRACKED_CHISELED_SOUL_NETHER_BRICKS.getDefaultState(), AbstractBlock.Settings.copy(CRACKED_CHISELED_SOUL_NETHER_BRICKS)));
	public static final Block CRACKED_CHISELED_SOUL_NETHER_BRICK_WALL = register("cracked_chiseled_soul_nether_brick_wall", new WallBlock(AbstractBlock.Settings.copy(CRACKED_CHISELED_SOUL_NETHER_BRICKS).solid()));
	
	public static final Block BLAZING_NETHER_BRICKS = register("blazing_nether_bricks", new HotFloorBlock(AbstractBlock.Settings.create().mapColor(MapColor.ORANGE).instrument(NoteBlockInstrument.BASEDRUM).requiresTool().strength(2.0f, 6.0f).sounds(BlockSoundGroup.NETHER_BRICKS).luminance(state -> 15)));
	public static final Block BLAZING_NETHER_BRICK_SLAB = register("blazing_nether_brick_slab", new HotFloorSlabBlock(AbstractBlock.Settings.copy(BLAZING_NETHER_BRICKS)));
	public static final Block BLAZING_NETHER_BRICK_STAIRS = register("blazing_nether_brick_stairs", new HotFloorStairsBlock(BLAZING_NETHER_BRICKS.getDefaultState(), AbstractBlock.Settings.copy(BLAZING_NETHER_BRICKS)));
	public static final Block BLAZING_NETHER_BRICK_WALL = register("blazing_nether_brick_wall", new HotFloorWallBlock(AbstractBlock.Settings.copy(BLAZING_NETHER_BRICKS).solid()));
	public static final Block BLAZING_NETHER_BRICK_FENCE = register("blazing_nether_brick_fence", new HotFloorFenceBlock(AbstractBlock.Settings.copy(BLAZING_NETHER_BRICKS).solid()));
	public static final Block BLAZING_NETHER_BRICK_FENCE_GATE = register("blazing_nether_brick_fence_gate", new HotFloorFenceGateBlock(SSWPWoodTypes.NETHER_BRICK, AbstractBlock.Settings.copy(BLAZING_NETHER_BRICKS).solid()));
	public static final Block CRACKED_BLAZING_NETHER_BRICKS = register("cracked_blazing_nether_bricks", new HotFloorBlock(AbstractBlock.Settings.copy(BLAZING_NETHER_BRICKS)));
	public static final Block CRACKED_BLAZING_NETHER_BRICK_SLAB = register("cracked_blazing_nether_brick_slab", new HotFloorSlabBlock(AbstractBlock.Settings.copy(CRACKED_BLAZING_NETHER_BRICKS)));
	public static final Block CRACKED_BLAZING_NETHER_BRICK_STAIRS = register("cracked_blazing_nether_brick_stairs", new HotFloorStairsBlock(CRACKED_BLAZING_NETHER_BRICKS.getDefaultState(), AbstractBlock.Settings.copy(CRACKED_BLAZING_NETHER_BRICKS)));
	public static final Block CRACKED_BLAZING_NETHER_BRICK_WALL = register("cracked_blazing_nether_brick_wall", new HotFloorWallBlock(AbstractBlock.Settings.copy(CRACKED_BLAZING_NETHER_BRICKS).solid()));
	public static final Block CRACKED_BLAZING_NETHER_BRICK_FENCE = register("cracked_blazing_nether_brick_fence", new HotFloorFenceBlock(AbstractBlock.Settings.copy(CRACKED_BLAZING_NETHER_BRICKS).solid()));
	public static final Block CRACKED_BLAZING_NETHER_BRICK_FENCE_GATE = register("cracked_blazing_nether_brick_fence_gate", new HotFloorFenceGateBlock(SSWPWoodTypes.NETHER_BRICK, AbstractBlock.Settings.copy(CRACKED_BLAZING_NETHER_BRICKS).solid()));
	public static final Block CHISELED_BLAZING_NETHER_BRICKS = register("chiseled_blazing_nether_bricks", new HotFloorBlock(AbstractBlock.Settings.copy(BLAZING_NETHER_BRICKS)));
	public static final Block CHISELED_BLAZING_NETHER_BRICK_SLAB = register("chiseled_blazing_nether_brick_slab", new HotFloorSlabBlock(AbstractBlock.Settings.copy(CHISELED_BLAZING_NETHER_BRICKS)));
	public static final Block CHISELED_BLAZING_NETHER_BRICK_STAIRS = register("chiseled_blazing_nether_brick_stairs", new HotFloorStairsBlock(CHISELED_BLAZING_NETHER_BRICKS.getDefaultState(), AbstractBlock.Settings.copy(CHISELED_BLAZING_NETHER_BRICKS)));
	public static final Block CHISELED_BLAZING_NETHER_BRICK_WALL = register("chiseled_blazing_nether_brick_wall", new HotFloorWallBlock(AbstractBlock.Settings.copy(CHISELED_BLAZING_NETHER_BRICKS).solid()));
	public static final Block CRACKED_CHISELED_BLAZING_NETHER_BRICKS = register("cracked_chiseled_blazing_nether_bricks", new HotFloorBlock(AbstractBlock.Settings.copy(BLAZING_NETHER_BRICKS)));
	public static final Block CRACKED_CHISELED_BLAZING_NETHER_BRICK_SLAB = register("cracked_chiseled_blazing_nether_brick_slab", new HotFloorSlabBlock(AbstractBlock.Settings.copy(CRACKED_CHISELED_BLAZING_NETHER_BRICKS)));
	public static final Block CRACKED_CHISELED_BLAZING_NETHER_BRICK_STAIRS = register("cracked_chiseled_blazing_nether_brick_stairs", new HotFloorStairsBlock(CRACKED_CHISELED_BLAZING_NETHER_BRICKS.getDefaultState(), AbstractBlock.Settings.copy(CRACKED_CHISELED_BLAZING_NETHER_BRICKS)));
	public static final Block CRACKED_CHISELED_BLAZING_NETHER_BRICK_WALL = register("cracked_chiseled_blazing_nether_brick_wall", new HotFloorWallBlock(AbstractBlock.Settings.copy(CRACKED_CHISELED_BLAZING_NETHER_BRICKS).solid()));
	
	public static final Block GLOWING_NETHER_BRICKS = register("glowing_nether_bricks", new Block(AbstractBlock.Settings.create().mapColor(MapColor.PALE_YELLOW).instrument(NoteBlockInstrument.BASEDRUM).requiresTool().strength(2.0f, 6.0f).sounds(BlockSoundGroup.NETHER_BRICKS).luminance(state -> 15)));
	public static final Block GLOWING_NETHER_BRICK_SLAB = register("glowing_nether_brick_slab", new SlabBlock(AbstractBlock.Settings.copy(GLOWING_NETHER_BRICKS)));
	public static final Block GLOWING_NETHER_BRICK_STAIRS = register("glowing_nether_brick_stairs", new StairsBlock(GLOWING_NETHER_BRICKS.getDefaultState(), AbstractBlock.Settings.copy(GLOWING_NETHER_BRICKS)));
	public static final Block GLOWING_NETHER_BRICK_WALL = register("glowing_nether_brick_wall", new WallBlock(AbstractBlock.Settings.copy(GLOWING_NETHER_BRICKS).solid()));
	public static final Block GLOWING_NETHER_BRICK_FENCE = register("glowing_nether_brick_fence", new FenceBlock(AbstractBlock.Settings.copy(GLOWING_NETHER_BRICKS).solid()));
	public static final Block GLOWING_NETHER_BRICK_FENCE_GATE = register("glowing_nether_brick_fence_gate", new FenceGateBlock(SSWPWoodTypes.NETHER_BRICK, AbstractBlock.Settings.copy(GLOWING_NETHER_BRICKS).solid()));
	public static final Block CRACKED_GLOWING_NETHER_BRICKS = register("cracked_glowing_nether_bricks", new Block(AbstractBlock.Settings.copy(GLOWING_NETHER_BRICKS)));
	public static final Block CRACKED_GLOWING_NETHER_BRICK_SLAB = register("cracked_glowing_nether_brick_slab", new SlabBlock(AbstractBlock.Settings.copy(CRACKED_GLOWING_NETHER_BRICKS)));
	public static final Block CRACKED_GLOWING_NETHER_BRICK_STAIRS = register("cracked_glowing_nether_brick_stairs", new StairsBlock(CRACKED_GLOWING_NETHER_BRICKS.getDefaultState(), AbstractBlock.Settings.copy(CRACKED_GLOWING_NETHER_BRICKS)));
	public static final Block CRACKED_GLOWING_NETHER_BRICK_WALL = register("cracked_glowing_nether_brick_wall", new WallBlock(AbstractBlock.Settings.copy(CRACKED_GLOWING_NETHER_BRICKS).solid()));
	public static final Block CRACKED_GLOWING_NETHER_BRICK_FENCE = register("cracked_glowing_nether_brick_fence", new FenceBlock(AbstractBlock.Settings.copy(CRACKED_GLOWING_NETHER_BRICKS).solid()));
	public static final Block CRACKED_GLOWING_NETHER_BRICK_FENCE_GATE = register("cracked_glowing_nether_brick_fence_gate", new FenceGateBlock(SSWPWoodTypes.NETHER_BRICK, AbstractBlock.Settings.copy(CRACKED_GLOWING_NETHER_BRICKS).solid()));
	public static final Block CHISELED_GLOWING_NETHER_BRICKS = register("chiseled_glowing_nether_bricks", new Block(AbstractBlock.Settings.copy(GLOWING_NETHER_BRICKS)));
	public static final Block CHISELED_GLOWING_NETHER_BRICK_SLAB = register("chiseled_glowing_nether_brick_slab", new SlabBlock(AbstractBlock.Settings.copy(CHISELED_GLOWING_NETHER_BRICKS)));
	public static final Block CHISELED_GLOWING_NETHER_BRICK_STAIRS = register("chiseled_glowing_nether_brick_stairs", new StairsBlock(CHISELED_GLOWING_NETHER_BRICKS.getDefaultState(), AbstractBlock.Settings.copy(CHISELED_GLOWING_NETHER_BRICKS)));
	public static final Block CHISELED_GLOWING_NETHER_BRICK_WALL = register("chiseled_glowing_nether_brick_wall", new WallBlock(AbstractBlock.Settings.copy(CHISELED_GLOWING_NETHER_BRICKS).solid()));
	public static final Block CRACKED_CHISELED_GLOWING_NETHER_BRICKS = register("cracked_chiseled_glowing_nether_bricks", new Block(AbstractBlock.Settings.copy(GLOWING_NETHER_BRICKS)));
	public static final Block CRACKED_CHISELED_GLOWING_NETHER_BRICK_SLAB = register("cracked_chiseled_glowing_nether_brick_slab", new SlabBlock(AbstractBlock.Settings.copy(CRACKED_CHISELED_GLOWING_NETHER_BRICKS)));
	public static final Block CRACKED_CHISELED_GLOWING_NETHER_BRICK_STAIRS = register("cracked_chiseled_glowing_nether_brick_stairs", new StairsBlock(CRACKED_CHISELED_GLOWING_NETHER_BRICKS.getDefaultState(), AbstractBlock.Settings.copy(CRACKED_CHISELED_GLOWING_NETHER_BRICKS)));
	public static final Block CRACKED_CHISELED_GLOWING_NETHER_BRICK_WALL = register("cracked_chiseled_glowing_nether_brick_wall", new WallBlock(AbstractBlock.Settings.copy(CRACKED_CHISELED_GLOWING_NETHER_BRICKS).solid()));
	
	public static final Block GHASTLY_NETHER_BRICKS = register("ghastly_nether_bricks", new Block(AbstractBlock.Settings.create().mapColor(MapColor.WHITE_GRAY).instrument(NoteBlockInstrument.BASEDRUM).requiresTool().strength(2.0f, 6.0f).sounds(BlockSoundGroup.NETHER_BRICKS).luminance(state -> 3)));
	public static final Block GHASTLY_NETHER_BRICK_SLAB = register("ghastly_nether_brick_slab", new SlabBlock(AbstractBlock.Settings.copy(GHASTLY_NETHER_BRICKS)));
	public static final Block GHASTLY_NETHER_BRICK_STAIRS = register("ghastly_nether_brick_stairs", new StairsBlock(GHASTLY_NETHER_BRICKS.getDefaultState(), AbstractBlock.Settings.copy(GHASTLY_NETHER_BRICKS)));
	public static final Block GHASTLY_NETHER_BRICK_WALL = register("ghastly_nether_brick_wall", new WallBlock(AbstractBlock.Settings.copy(GHASTLY_NETHER_BRICKS).solid()));
	public static final Block GHASTLY_NETHER_BRICK_FENCE = register("ghastly_nether_brick_fence", new FenceBlock(AbstractBlock.Settings.copy(GHASTLY_NETHER_BRICKS).solid()));
	public static final Block GHASTLY_NETHER_BRICK_FENCE_GATE = register("ghastly_nether_brick_fence_gate", new FenceGateBlock(SSWPWoodTypes.NETHER_BRICK, AbstractBlock.Settings.copy(GHASTLY_NETHER_BRICKS).solid()));
	public static final Block CRACKED_GHASTLY_NETHER_BRICKS = register("cracked_ghastly_nether_bricks", new Block(AbstractBlock.Settings.copy(GHASTLY_NETHER_BRICKS)));
	public static final Block CRACKED_GHASTLY_NETHER_BRICK_SLAB = register("cracked_ghastly_nether_brick_slab", new SlabBlock(AbstractBlock.Settings.copy(CRACKED_GHASTLY_NETHER_BRICKS)));
	public static final Block CRACKED_GHASTLY_NETHER_BRICK_STAIRS = register("cracked_ghastly_nether_brick_stairs", new StairsBlock(CRACKED_GHASTLY_NETHER_BRICKS.getDefaultState(), AbstractBlock.Settings.copy(CRACKED_GHASTLY_NETHER_BRICKS)));
	public static final Block CRACKED_GHASTLY_NETHER_BRICK_WALL = register("cracked_ghastly_nether_brick_wall", new WallBlock(AbstractBlock.Settings.copy(CRACKED_GHASTLY_NETHER_BRICKS).solid()));
	public static final Block CRACKED_GHASTLY_NETHER_BRICK_FENCE = register("cracked_ghastly_nether_brick_fence", new FenceBlock(AbstractBlock.Settings.copy(CRACKED_GHASTLY_NETHER_BRICKS).solid()));
	public static final Block CRACKED_GHASTLY_NETHER_BRICK_FENCE_GATE = register("cracked_ghastly_nether_brick_fence_gate", new FenceGateBlock(SSWPWoodTypes.NETHER_BRICK, AbstractBlock.Settings.copy(CRACKED_GHASTLY_NETHER_BRICKS).solid()));
	public static final Block CHISELED_GHASTLY_NETHER_BRICKS = register("chiseled_ghastly_nether_bricks", new Block(AbstractBlock.Settings.copy(GHASTLY_NETHER_BRICKS)));
	public static final Block CHISELED_GHASTLY_NETHER_BRICK_SLAB = register("chiseled_ghastly_nether_brick_slab", new SlabBlock(AbstractBlock.Settings.copy(CHISELED_GHASTLY_NETHER_BRICKS)));
	public static final Block CHISELED_GHASTLY_NETHER_BRICK_STAIRS = register("chiseled_ghastly_nether_brick_stairs", new StairsBlock(CHISELED_GHASTLY_NETHER_BRICKS.getDefaultState(), AbstractBlock.Settings.copy(CHISELED_GHASTLY_NETHER_BRICKS)));
	public static final Block CHISELED_GHASTLY_NETHER_BRICK_WALL = register("chiseled_ghastly_nether_brick_wall", new WallBlock(AbstractBlock.Settings.copy(CHISELED_GHASTLY_NETHER_BRICKS).solid()));
	public static final Block CRACKED_CHISELED_GHASTLY_NETHER_BRICKS = register("cracked_chiseled_ghastly_nether_bricks", new Block(AbstractBlock.Settings.copy(GHASTLY_NETHER_BRICKS)));
	public static final Block CRACKED_CHISELED_GHASTLY_NETHER_BRICK_SLAB = register("cracked_chiseled_ghastly_nether_brick_slab", new SlabBlock(AbstractBlock.Settings.copy(CRACKED_CHISELED_GHASTLY_NETHER_BRICKS)));
	public static final Block CRACKED_CHISELED_GHASTLY_NETHER_BRICK_STAIRS = register("cracked_chiseled_ghastly_nether_brick_stairs", new StairsBlock(CRACKED_CHISELED_GHASTLY_NETHER_BRICKS.getDefaultState(), AbstractBlock.Settings.copy(CRACKED_CHISELED_GHASTLY_NETHER_BRICKS)));
	public static final Block CRACKED_CHISELED_GHASTLY_NETHER_BRICK_WALL = register("cracked_chiseled_ghastly_nether_brick_wall", new WallBlock(AbstractBlock.Settings.copy(CRACKED_CHISELED_GHASTLY_NETHER_BRICKS).solid()));
	
	public static final Block CRACKED_END_STONE_BRICKS = register("cracked_end_stone_bricks", new Block(AbstractBlock.Settings.copy(Blocks.END_STONE_BRICKS)));
	public static final Block CRACKED_END_STONE_BRICK_SLAB = register("cracked_end_stone_brick_slab", new SlabBlock(AbstractBlock.Settings.copy(CRACKED_END_STONE_BRICKS)));
	public static final Block CRACKED_END_STONE_BRICK_STAIRS = register("cracked_end_stone_brick_stairs", new StairsBlock(CRACKED_END_STONE_BRICKS.getDefaultState(), AbstractBlock.Settings.copy(CRACKED_END_STONE_BRICKS)));
	public static final Block CRACKED_END_STONE_BRICK_WALL = register("cracked_end_stone_brick_wall", new WallBlock(AbstractBlock.Settings.copy(CRACKED_END_STONE_BRICKS).solid()));
	
	public static final Block CRACKED_QUARTZ_BRICKS = register("cracked_quartz_bricks", new Block(AbstractBlock.Settings.copy(Blocks.QUARTZ_BRICKS)));
	public static final Block CRACKED_QUARTZ_BRICK_SLAB = register("cracked_quartz_brick_slab", new SlabBlock(AbstractBlock.Settings.copy(CRACKED_QUARTZ_BRICKS)));
	public static final Block CRACKED_QUARTZ_BRICK_STAIRS = register("cracked_quartz_brick_stairs", new StairsBlock(CRACKED_QUARTZ_BRICKS.getDefaultState(), AbstractBlock.Settings.copy(CRACKED_QUARTZ_BRICKS)));
	public static final Block CRACKED_QUARTZ_BRICK_WALL = register("cracked_quartz_brick_wall", new WallBlock(AbstractBlock.Settings.copy(CRACKED_QUARTZ_BRICKS).solid()));
	
	public static final Block INFESTED_MOSSY_STONE = register("infested_mossy_stone", new InfestedBlock(MOSSY_STONE, AbstractBlock.Settings.create().mapColor(MapColor.LIGHT_BLUE_GRAY)));
	public static final Block INFESTED_CRACKED_MOSSY_STONE_BRICKS = register("infested_cracked_mossy_stone_bricks", new InfestedBlock(CRACKED_MOSSY_STONE_BRICKS, AbstractBlock.Settings.create().mapColor(MapColor.LIGHT_BLUE_GRAY)));
	public static final Block INFESTED_CRACKED_CHISELED_STONE_BRICKS = register("infested_cracked_chiseled_stone_bricks", new InfestedBlock(CRACKED_CHISELED_STONE_BRICKS, AbstractBlock.Settings.create().mapColor(MapColor.LIGHT_BLUE_GRAY)));
	public static final Block INFESTED_MOSSY_CHISELED_STONE_BRICKS = register("infested_mossy_chiseled_stone_bricks", new InfestedBlock(MOSSY_CHISELED_STONE_BRICKS, AbstractBlock.Settings.create().mapColor(MapColor.LIGHT_BLUE_GRAY)));
	public static final Block INFESTED_CRACKED_MOSSY_CHISELED_STONE_BRICKS = register("infested_cracked_mossy_chiseled_stone_bricks", new InfestedBlock(CRACKED_MOSSY_CHISELED_STONE_BRICKS, AbstractBlock.Settings.create().mapColor(MapColor.LIGHT_BLUE_GRAY)));
	
	public static final Block INFESTED_MOSSY_GRANITE = register("infested_mossy_granite", new InfestedBlock(MOSSY_GRANITE, AbstractBlock.Settings.create().mapColor(MapColor.TERRACOTTA_BROWN)));
	public static final Block INFESTED_COBBLED_GRANITE = register("infested_cobbled_granite", new InfestedBlock(COBBLED_GRANITE, AbstractBlock.Settings.create().mapColor(MapColor.TERRACOTTA_BROWN)));
	public static final Block INFESTED_MOSSY_COBBLED_GRANITE = register("infested_mossy_cobbled_granite", new InfestedBlock(MOSSY_COBBLED_GRANITE, AbstractBlock.Settings.create().mapColor(MapColor.TERRACOTTA_BROWN)));
	public static final Block INFESTED_GRANITE_BRICKS = register("infested_granite_bricks", new InfestedBlock(GRANITE_BRICKS, AbstractBlock.Settings.create().mapColor(MapColor.TERRACOTTA_BROWN)));
	public static final Block INFESTED_CRACKED_GRANITE_BRICKS = register("infested_cracked_granite_bricks", new InfestedBlock(CRACKED_GRANITE_BRICKS, AbstractBlock.Settings.create().mapColor(MapColor.TERRACOTTA_BROWN)));
	public static final Block INFESTED_MOSSY_GRANITE_BRICKS = register("infested_mossy_granite_bricks", new InfestedBlock(MOSSY_GRANITE_BRICKS, AbstractBlock.Settings.create().mapColor(MapColor.TERRACOTTA_BROWN)));
	public static final Block INFESTED_CRACKED_MOSSY_GRANITE_BRICKS = register("infested_cracked_mossy_granite_bricks", new InfestedBlock(CRACKED_MOSSY_GRANITE_BRICKS, AbstractBlock.Settings.create().mapColor(MapColor.TERRACOTTA_BROWN)));
	
	public static final Block INFESTED_MOSSY_DIORITE = register("infested_mossy_diorite", new InfestedBlock(MOSSY_DIORITE, AbstractBlock.Settings.create().mapColor(MapColor.WHITE_GRAY)));
	public static final Block INFESTED_COBBLED_DIORITE = register("infested_cobbled_diorite", new InfestedBlock(COBBLED_DIORITE, AbstractBlock.Settings.create().mapColor(MapColor.WHITE_GRAY)));
	public static final Block INFESTED_MOSSY_COBBLED_DIORITE = register("infested_mossy_cobbled_diorite", new InfestedBlock(MOSSY_COBBLED_DIORITE, AbstractBlock.Settings.create().mapColor(MapColor.WHITE_GRAY)));
	public static final Block INFESTED_DIORITE_BRICKS = register("infested_diorite_bricks", new InfestedBlock(DIORITE_BRICKS, AbstractBlock.Settings.create().mapColor(MapColor.WHITE_GRAY)));
	public static final Block INFESTED_CRACKED_DIORITE_BRICKS = register("infested_cracked_diorite_bricks", new InfestedBlock(CRACKED_DIORITE_BRICKS, AbstractBlock.Settings.create().mapColor(MapColor.WHITE_GRAY)));
	public static final Block INFESTED_MOSSY_DIORITE_BRICKS = register("infested_mossy_diorite_bricks", new InfestedBlock(MOSSY_DIORITE_BRICKS, AbstractBlock.Settings.create().mapColor(MapColor.WHITE_GRAY)));
	public static final Block INFESTED_CRACKED_MOSSY_DIORITE_BRICKS = register("infested_cracked_mossy_diorite_bricks", new InfestedBlock(CRACKED_MOSSY_DIORITE_BRICKS, AbstractBlock.Settings.create().mapColor(MapColor.WHITE_GRAY)));
	
	public static final Block INFESTED_MOSSY_ANDESITE = register("infested_mossy_andesite", new InfestedBlock(MOSSY_ANDESITE, AbstractBlock.Settings.create().mapColor(MapColor.LIGHT_BLUE_GRAY)));
	public static final Block INFESTED_COBBLED_ANDESITE = register("infested_cobbled_andesite", new InfestedBlock(COBBLED_ANDESITE, AbstractBlock.Settings.create().mapColor(MapColor.LIGHT_BLUE_GRAY)));
	public static final Block INFESTED_MOSSY_COBBLED_ANDESITE = register("infested_mossy_cobbled_andesite", new InfestedBlock(MOSSY_COBBLED_ANDESITE, AbstractBlock.Settings.create().mapColor(MapColor.LIGHT_BLUE_GRAY)));
	public static final Block INFESTED_ANDESITE_BRICKS = register("infested_andesite_bricks", new InfestedBlock(ANDESITE_BRICKS, AbstractBlock.Settings.create().mapColor(MapColor.LIGHT_BLUE_GRAY)));
	public static final Block INFESTED_CRACKED_ANDESITE_BRICKS = register("infested_cracked_andesite_bricks", new InfestedBlock(CRACKED_ANDESITE_BRICKS, AbstractBlock.Settings.create().mapColor(MapColor.LIGHT_BLUE_GRAY)));
	public static final Block INFESTED_MOSSY_ANDESITE_BRICKS = register("infested_mossy_andesite_bricks", new InfestedBlock(MOSSY_ANDESITE_BRICKS, AbstractBlock.Settings.create().mapColor(MapColor.LIGHT_BLUE_GRAY)));
	public static final Block INFESTED_CRACKED_MOSSY_ANDESITE_BRICKS = register("infested_cracked_mossy_andesite_bricks", new InfestedBlock(CRACKED_MOSSY_ANDESITE_BRICKS, AbstractBlock.Settings.create().mapColor(MapColor.LIGHT_BLUE_GRAY)));
	
	public static final Block INFESTED_MOSSY_DEEPSLATE = register("infested_mossy_deepslate", new RotatedInfestedBlock(MOSSY_DEEPSLATE, AbstractBlock.Settings.create().mapColor(MapColor.DEEPSLATE_GRAY).sounds(BlockSoundGroup.DEEPSLATE)));
	public static final Block INFESTED_MOSSY_COBBLED_DEEPSLATE = register("infested_mossy_cobbled_deepslate", new InfestedBlock(MOSSY_COBBLED_DEEPSLATE, AbstractBlock.Settings.create().mapColor(MapColor.DEEPSLATE_GRAY).sounds(BlockSoundGroup.DEEPSLATE)));
	public static final Block INFESTED_MOSSY_DEEPSLATE_BRICKS = register("infested_mossy_deepslate_bricks", new InfestedBlock(MOSSY_DEEPSLATE_BRICKS, AbstractBlock.Settings.create().mapColor(MapColor.DEEPSLATE_GRAY).sounds(BlockSoundGroup.DEEPSLATE_BRICKS)));
	public static final Block INFESTED_CRACKED_MOSSY_DEEPSLATE_BRICKS = register("infested_cracked_mossy_deepslate_bricks", new InfestedBlock(CRACKED_MOSSY_DEEPSLATE_BRICKS, AbstractBlock.Settings.create().mapColor(MapColor.DEEPSLATE_GRAY).sounds(BlockSoundGroup.DEEPSLATE_BRICKS)));
	public static final Block INFESTED_MOSSY_DEEPSLATE_TILES = register("infested_mossy_deepslate_tiles", new InfestedBlock(MOSSY_DEEPSLATE_TILES, AbstractBlock.Settings.create().mapColor(MapColor.DEEPSLATE_GRAY).sounds(BlockSoundGroup.DEEPSLATE_TILES)));
	public static final Block INFESTED_CRACKED_MOSSY_DEEPSLATE_TILES = register("infested_cracked_mossy_deepslate_tiles", new InfestedBlock(CRACKED_MOSSY_DEEPSLATE_TILES, AbstractBlock.Settings.create().mapColor(MapColor.DEEPSLATE_GRAY).sounds(BlockSoundGroup.DEEPSLATE_TILES)));
	
	public static final Block INFESTED_MOSSY_TUFF = register("infested_mossy_tuff", new InfestedBlock(MOSSY_TUFF, AbstractBlock.Settings.create().mapColor(MapColor.TERRACOTTA_LIGHT_GRAY).sounds(BlockSoundGroup.TUFF)));
	public static final Block INFESTED_CRACKED_TUFF_BRICKS = register("infested_cracked_tuff_bricks", new InfestedBlock(CRACKED_TUFF_BRICKS, AbstractBlock.Settings.create().mapColor(MapColor.TERRACOTTA_LIGHT_GRAY).sounds(BlockSoundGroup.TUFF_BRICKS)));
	public static final Block INFESTED_MOSSY_TUFF_BRICKS = register("infested_mossy_tuff_bricks", new InfestedBlock(MOSSY_TUFF_BRICKS, AbstractBlock.Settings.create().mapColor(MapColor.TERRACOTTA_LIGHT_GRAY).sounds(BlockSoundGroup.TUFF_BRICKS)));
	public static final Block INFESTED_CRACKED_MOSSY_TUFF_BRICKS = register("infested_cracked_mossy_tuff_bricks", new InfestedBlock(CRACKED_MOSSY_TUFF_BRICKS, AbstractBlock.Settings.create().mapColor(MapColor.TERRACOTTA_LIGHT_GRAY).sounds(BlockSoundGroup.TUFF_BRICKS)));
	public static final Block INFESTED_CRACKED_CHISELED_TUFF_BRICKS = register("infested_cracked_chiseled_tuff_bricks", new InfestedBlock(CRACKED_CHISELED_TUFF_BRICKS, AbstractBlock.Settings.create().mapColor(MapColor.TERRACOTTA_LIGHT_GRAY).sounds(BlockSoundGroup.TUFF_BRICKS)));
	public static final Block INFESTED_MOSSY_CHISELED_TUFF_BRICKS = register("infested_mossy_chiseled_tuff_bricks", new InfestedBlock(MOSSY_CHISELED_TUFF_BRICKS, AbstractBlock.Settings.create().mapColor(MapColor.TERRACOTTA_LIGHT_GRAY).sounds(BlockSoundGroup.TUFF_BRICKS)));
	public static final Block INFESTED_CRACKED_MOSSY_CHISELED_TUFF_BRICKS = register("infested_cracked_mossy_chiseled_tuff_bricks", new InfestedBlock(CRACKED_MOSSY_CHISELED_TUFF_BRICKS, AbstractBlock.Settings.create().mapColor(MapColor.TERRACOTTA_LIGHT_GRAY).sounds(BlockSoundGroup.TUFF_BRICKS)));
	
	public static Block register(String name, Block block) {
		return Registry.register(Registries.BLOCK, Identifier.of(MSMain.MOD_ID, name), block);
	}
}